Mellanox/libvma

contrib/test_jenkins.sh
added jenkins script to branch : experimental_256B
=> added basic jenkins script

contrib/jenkins_tests/cov.sh, contrib/jenkins_tests/globals.sh, contrib/jenkins_tests/rpm.sh, contrib/jenkins_tests/style.sh, contrib/jenkins_tests/test.sh, contrib/jenkins_tests/vg.sh, contrib/test_jenkins.sh
Added basic verification capabilities
- rpm
- build gcc/icc
- cov
valgrind will be later
style is disabled (should be added later)
@Di0gen could you look at this PR
=> issue: 770746 Add jenkins check support on github pull request

configure.ac, src/stats/stats_reader.cpp, src/vma/dev/cq_mgr.cpp, src/vma/iomux/select_call.cpp, src/vma/proto/flow_tuple.cpp, src/vma/proto/flow_tuple.h, src/vma/proto/neighbour.cpp, src/vma/proto/vma_lwip.h, src/vma/sock/sock-redirect.cpp, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_udp.cpp, src/vma/sock/sockinfo_udp.h
This changes adapt code to be used with Intel Compiler.
=> issue: 773091 Add Intel compiler support

src/vma/sock/sock-redirect.cpp
Log FINE "EXIT: ...rc = ??" on epoll_wait() and poll() where missing
=> issue: 777322 update logging on iomux flows

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.0.2 *******************

src/vma/main.h, src/vma/sock/sock-redirect.cpp, src/vma/util/sys_vars.cpp, src/vma/util/sys_vars.h
=> issue: 778287 - Fix usage of get_env_params() method in mce_sys_var struct

contrib/jenkins_tests/compiler.sh, contrib/jenkins_tests/cov.sh, contrib/jenkins_tests/globals.sh, contrib/jenkins_tests/rpm.sh, contrib/jenkins_tests/style.sh, contrib/jenkins_tests/test.sh, contrib/jenkins_tests/vg.sh, contrib/test_jenkins.sh, tests/valgrind_rdma.supp
This commit enable compiler, valgrind and test units
@Di0gen could you look at.
tap-files can be found at $WORKSPACE/jenkins folder
=> issue: 770746 Extend jenkins check

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.0.3 *******************

tests/testbed/README, tests/testbed/testbed.c
Description:
- This application includes sender, engine, receiver units.
- sender and receiver are located on the same node when engine on another.
- Each connection in sender program constantly sends messages to engine
program at a specific message rate.
- The engine redirects received messages to the connections with receiver process.
@alexvm please review
=> issue 781492: Add testbed application

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.0.4 *******************

src/vlogger/Makefile.am
This change fixes rpmbuild --rebuild failure.
=> issue: 793030 Fix rpm rebuild failure

src/stats/stats_publisher.cpp
Signed-off-by: Daniel Libenson <daneilli@mellanox.com>
=> issue: 784234 fixed epoll is not cleared from vma_stats

contrib/jenkins_tests/globals.sh, contrib/jenkins_tests/test.sh, contrib/test_jenkins.sh
Current check services experimental_256B branch only
at the moment but can be extended later for different
purpose.
see https://github.com/Mellanox/libvma/pull/93 for details
this commit can be moved to experimental_256B branch after merge
=> issue: 770746 Add environment check before starting

src/vma/sock/sockinfo_udp.cpp
In case we detect sockets are bound to not offloaded interfaces we
should remove them from the offloaded list (remove from fd_colelction).
Calling setPassthrough() in bind() flow will handle that.
If this not-offloaded socket is called from select(), it will not be
mapped as offloaded and select(0 will refrain from checking the RING's
for events.
Also the vma_stats will not see these fd's as offloaded.
=> issue: 777358 un-offload UDP socket that is bound to any non-offloaded interfaces (like loopback (127.0.0.1)

tests/testbed/testbed.c
This commit consists of:
- Add read/write non-blocking support. It can be controlled
by BLOCKING_READ_ENABLED=[0|1] and BLOCKING_WRITE_ENABLED=[0|1]
- Fix several bugs
- Add mlock/munlock for statistic memory region
@alexvm could you look at
=> issue: 781492 Add VMA zcopy API support to testbed

autogen.sh, contrib/jenkins_tests/compiler.sh, contrib/jenkins_tests/cov.sh, contrib/jenkins_tests/rpm.sh, contrib/jenkins_tests/style.sh, contrib/jenkins_tests/test.sh, contrib/jenkins_tests/vg.sh, contrib/test_jenkins.sh, coverity_vma_config.xml
This change enables src and bin rpm check
=> issue: 786406 Run check for src RPM in jenkins

contrib/jenkins_tests/compiler.sh, contrib/jenkins_tests/cov.sh, contrib/jenkins_tests/globals.sh, contrib/jenkins_tests/rpm.sh, contrib/jenkins_tests/style.sh, contrib/jenkins_tests/test.sh, contrib/jenkins_tests/vg.sh, contrib/test_jenkins.sh, tests/valgrind_rdma.supp
see related in master 
https://github.com/Mellanox/libvma/commit/a96249
https://github.com/Mellanox/libvma/commit/f39afa0
https://github.com/Mellanox/libvma/commit/f4ddf05
https://github.com/Mellanox/libvma/commit/312e53
=> issue: 770746 Update jenkins from master

src/vma/lwip/tcp.h
=> issue: 806219 Fix segfault when running with CTL_THREAD_NO_WAKEUP

src/vma/dev/qp_mgr.cpp, src/vma/proto/dst_entry.h, src/vma/util/sys_vars.h
=> issue: 820855 explicitly set QP capability of max send SG to 2 (workaround for CX4/Upstream OFED)

src/vma/config_parser.c, src/vma/main.cpp
=> issue: 820858 CX3- update message regarding no steering rules default setting in upstream

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.1.1 *******************

src/vma/lwip/ip.h, src/vma/lwip/opt.h, src/vma/lwip/tcp.c, src/vma/lwip/tcp_impl.h, src/vma/lwip/tcp_in.c
=> issue: 825842 Fix compilation errors while enabling LWIP debug options

src/stats/stats_reader.cpp
=> issue: 822562 Fix segmentation fault in vma_stats while using long

src/vma/sock/sockinfo_tcp.cpp
=> issue: 803783 Allow local TCP connections for offlaoded bounded listen sockets

src/vma/dev/buffer_pool.cpp, src/vma/dev/ib_ctx_handler_collection.cpp, src/vma/dev/net_device_table_mgr.cpp, src/vma/event/event_handler_manager.cpp, src/vma/proto/ip_frag.cpp, src/vma/proto/neighbour_table_mgr.cpp, src/vma/proto/vma_lwip.cpp, src/vma/sock/sockinfo_tcp.cpp, src/vma/util/utils.h
Use instead throw_vma_exception("informative-message")
=> issue: 631198 Remove macro throw_vma_exception_no_msg

contrib/jenkins_tests/rpm.sh
Automake 1.10.1 has a bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=456632
=> issue: 770746 Add workaround for automake 1.10.1

contrib/jenkins_tests/build.sh, contrib/jenkins_tests/compiler.sh, contrib/jenkins_tests/cov.sh, contrib/jenkins_tests/globals.sh, contrib/jenkins_tests/rpm.sh, contrib/jenkins_tests/test.sh, contrib/jenkins_tests/vg.sh, contrib/test_jenkins.sh
This change allows to check inbox/upstream
Also added few build configuration check such as
1. default
2. --enable-debug
3. --enable-opt-log
=> issue: 827622 Add jenkins support for inbox

src/vma/dev/net_device_table_mgr.cpp
log: while mapping devices in bring up use base_name for vlan/alias over bond
=> issue: 844457 fix vlan over bond failure on bring up

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.1.2 *******************

src/vma/sock/sockinfo_tcp.cpp
Add locking to protect against simultaneous pcb changes by user applications and internal thread
=> issue: 825799 Add locking to setsockopt() TCP

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.1.3 *******************

src/vma/util/utils.cpp, src/vma/util/utils.h
=> issue: 848239 Remove unused utility functions

src/vma/sock/sock-redirect.cpp, src/vma/sock/sockinfo_udp.cpp, src/vma/vma_extra.h
Enabled vma_poll udp functionality support
Signed-off-by: Sergey Lykov <serglelv@gmail.com>
@OphirMunk @alexvm @rosenbaumalex @igor-ivanov 
Could you please review and comment?
=> issue: 807404 Add UDP support for vma_poll

README.md
Add badges for:
1. Version
2. Coverity Scan
=> issue: 847360 update github's README.md file

src/vma/dev/ring_bond.cpp, src/vma/dev/ring_simple.cpp, src/vma/util/utils.cpp
@OphirMunk please look at this.
=> issue: 848172 Fix coverity 8.5 version

src/vma/dev/ring_simple.cpp, src/vma/lwip/cc_cubic.h, src/vma/lwip/tcp_in.c, src/vma/proto/dst_entry.cpp, src/vma/proto/dst_entry_udp_mc.cpp
=> issue: 848172 Fix csbuild report 'value stored is never read' errors

src/vma/sock/sockinfo.cpp, src/vma/sock/sockinfo.h, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_udp.cpp
Initialization of the m_p_rx_ring is moved to attach_as_uc_receiver. Please review.
@igor-ivanov @rosenbaumalex @alexvm @OphirMunk
=> issue: 851773 Added initialization of m_p_rx_ring in connect 

tests/throughput_test/bandwidth_test.c
The test bandwidth_test was updated to support vma_poll udp. Please review.
@igor-ivanov @rosenbaumalex @OphirMunk
=> issue: 807404 vma_poll udp was added to throughput_test

src/vma/dev/net_device_table_mgr.cpp
=> issue: 843662 fix log WARNING to DEBUG in case not an mlx4 driver on IPoIB interface

configure.ac, src/vma/hw/mlx5/wqe.h
=> issue: 755772 configure time check for mlx5_hw features in MLNX_OFED

src/vma/sock/sockinfo_udp.cpp
Signed-off-by: Daniel Libenson <daneilli@mellanox.com>
=> issue: 749133 Fix setsockopt IGMP struct size check

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.1.5 *******************

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.1.6 *******************

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.1.7 *******************

src/vma/iomux/epoll_wait_call.h, src/vma/iomux/io_mux_call.h, src/vma/sock/sock-redirect.cpp
=> issue: 888030 Fix potential OS sockets starvation in epoll_wait()

contrib/jenkins_tests/globals.sh
=> issue: 894272 jenkins: Disable IPoIB verification for CX4

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.2.2 *******************

src/vma/dev/ring.cpp, src/vma/dev/ring.h, src/vma/dev/ring_simple.cpp, src/vma/sock/sockinfo.cpp
=> issue: 896067 Remove ring event during socket close

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.2.7 *******************

src/vma/Makefile.am, src/vma/dev/cq_mgr.cpp, src/vma/dev/cq_mgr.h, src/vma/dev/cq_mgr_mlx5.cpp, src/vma/dev/cq_mgr_mlx5.h, src/vma/dev/cq_mgr_mlx5.inl, src/vma/dev/cq_mgr_mp.cpp, src/vma/sock/sockinfo.cpp, src/vma/sock/sockinfo.h
Signed-off-by: AlaAyesh <aayesh@asaltech.com>
=> issue: 1055915 Fix tcp degragation related to MP_RQ

src/stats/stats_reader.cpp
=> issue: 1190606 VMA stats - Remove timewait interval in last cycle

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.4.10 *******************

src/vma/dev/ib_ctx_handler.cpp, src/vma/dev/ib_ctx_handler.h, src/vma/dev/qp_mgr.cpp, src/vma/dev/qp_mgr_mp.cpp, src/vma/dev/ring_eth_cb.cpp, src/vma/dev/ring_simple.cpp, src/vma/util/verbs_extra.h
This commit remove unneeded fields from ib_ctx class
=> issue: 1080998 optimize ib_ctx class

Makefile.am, build/libvma.spec.in, build/libvma_fedora.spec, configure.ac, contrib/scripts/vma.service.in, debian/libvma.install, tools/daemon/daemon.c, tools/daemon/loop.c
VMA daemon can be controled by systemd.
It supports service auto recovery ability.
=> issue: 1214451 Add systemd support for daemon

src/vma/dev/cq_mgr_mp.cpp, src/vma/dev/cq_mgr_mp.h, src/vma/dev/ring_eth_cb.cpp
=> issue: 1148076 Remove volatile when handling CQE in MP_RQ

src/vma/proto/route_table_mgr.cpp, src/vma/proto/route_val.h, src/vma/proto/rule_table_mgr.cpp, src/vma/proto/rule_val.h
This commit adds support for parsing route and rule
extended table_id
=> issue:1214066 add support for extended table id

src/vma/dev/cq_mgr.cpp, src/vma/dev/cq_mgr.h, src/vma/dev/cq_mgr.inl
=> issue: 1247022 fix typo in CQ struct  debth->debt

src/vma/sock/sock-redirect.cpp, src/vma/vma_extra.h, tests/gtest/vma/vma_ring.cc, tests/testbed/testbed.c
socketxtreme_get_socket_rings_fds -> get_socket_rings_fds
socketxtreme_get_socket_rings_num -> get_socket_rings_num
Those functions are not related only to sockeXtreme
=> issue: 1248185 revert some vma_extra sockeXtreme names change

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.5.1 *******************

contrib/valgrind/valgrind_vma.supp
=> issue: 1151606 Modify valgrind suppression file

contrib/valgrind/valgrind_vma.supp, src/vma/dev/allocator.cpp, src/vma/dev/allocator.h, src/vma/dev/cq_mgr_mp.cpp, src/vma/dev/ib_ctx_handler.cpp, src/vma/dev/ib_ctx_handler.h, src/vma/dev/qp_mgr_mp.cpp, src/vma/dev/qp_mgr_mp.h, src/vma/dev/ring_eth_cb.cpp, src/vma/dev/ring_eth_cb.h, src/vma/dev/ring_profile.cpp, src/vma/dev/ring_simple.cpp, src/vma/sock/sockinfo.cpp, src/vma/sock/sockinfo.h, src/vma/util/verbs_extra.h, src/vma/vma_extra.h
=> issue: 1055916 add support for UMR in MP-RQ 

src/vma/proto/dst_entry.h, src/vma/sock/sock-redirect.cpp, src/vma/sock/socket_fd_api.h, src/vma/sock/sockinfo.cpp, src/vma/sock/sockinfo.h, src/vma/sock/sockinfo_udp.cpp, src/vma/vma_extra.h
=> issue: 1226473 expose network header created by VMA using new extra_api

src/vma/proto/neighbour.cpp
=> issue: 1247358 Fix crash when VMA could not resolve neighbour

build/build_deb.sh, debian/libvma.install
This issue relate system w/o systemd init system.
=> issue: 1256248 Fix issue with Debian package

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.5.2 *******************

src/vma/dev/ring.h, src/vma/dev/ring_simple.cpp, src/vma/dev/ring_simple.h, src/vma/proto/dst_entry.h, src/vma/sock/sock-redirect.cpp, src/vma/sock/socket_fd_api.h, src/vma/sock/sockinfo_udp.cpp, src/vma/sock/sockinfo_udp.h, src/vma/vma_extra.h
=> issue: 1248705 add extra api to get ring TX fd from socket

src/vma/dev/ib_ctx_handler.cpp, src/vma/dev/ib_ctx_handler.h, src/vma/dev/net_device_table_mgr.cpp, src/vma/dev/net_device_table_mgr.h, src/vma/dev/net_device_val.cpp, src/vma/dev/net_device_val.h, src/vma/util/utils.cpp, src/vma/util/utils.h
=> issue: 1264431 Detect device port without rdma_cm

src/stats/stats_printer.cpp, src/stats/stats_reader.cpp, src/vma/lwip/ip.h
Statistics regarding ring interrupts, moderations and retransmissions
will be published only when the value is not zero.
Signed-off-by: Liran Oz <lirano@mellanox.com
=> issue: 1272179 Arrange Ring statistics

src/vma/dev/qp_mgr_eth_direct.cpp, src/vma/dev/qp_mgr_eth_direct.h
=> issue: 1226478 fix direct QP and CQ destruction

src/vma/iomux/epoll_wait_call.cpp, src/vma/iomux/epoll_wait_call.h, src/vma/iomux/io_mux_call.cpp, src/vma/iomux/io_mux_call.h
=> issue: 1262198 Fix epoll_wait returns fd event twice in single call

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.5.3 *******************

build/build_deb.sh
=> issue: 1279340 Fix issue in build_deb.sh

src/vma/dev/ring_bond.h
=> issue: 1280126 Fix 94e9e93 performance TCP degradation

contrib/valgrind/valgrind_vma.supp, src/vma/dev/ring_eth_direct.cpp
=> issue: 1226478 add valgrind detection macro

src/vma/dev/ring_bond.cpp
TAP interface name should be based on the process id and the file
descriptor on the TAP device.
=> issue: 1279684 Modify TAP interface name

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.5.5 *******************

contrib/jenkins_tests/globals.sh, contrib/test_jenkins.sh, src/vma/dev/net_device_table_mgr.cpp, tests/gtest/README
=> issue: 1172298 Rename jenkins traget vmapoll with socketxtreme

src/vma/Makefile.am, src/vma/dev/dm_mgr.cpp, src/vma/dev/dm_mgr.h, src/vma/dev/ib_ctx_handler.cpp, src/vma/dev/qp_mgr_eth_mlx5.cpp, src/vma/dev/qp_mgr_eth_mlx5.h
This will also rename dm_context class to dm_mgr.
=> issue: 1284253 Move dm_context class from util to dev

tools/daemon/flow.c
These changes implement selection of node id inside bucket
basing on internal storage information comparing with
previous logic based on destination port number.
It allows to provide more flexible solution but requires
additional memory and operations.
=> issue: 1262610 Change bucket:node choice for 5t flow

contrib/jenkins_tests/gtest.sh, tests/gtest/Makefile.am, tests/gtest/common/def.h, tests/gtest/common/sys.cc, tests/gtest/common/sys.h, tests/gtest/mix/mix_base.cc, tests/gtest/mix/mix_base.h, tests/gtest/mix/mix_list.cc, tests/gtest/mix/sg_array.cc, tests/gtest/vmad/vmad_base.cc, tests/gtest/vmad/vmad_base.h, tests/gtest/vmad/vmad_bitmap.cc, tests/gtest/vmad/vmad_flow.cc, tests/gtest/vmad/vmad_hash.cc, tests/gtest/vmad/vmad_init.cc, tests/gtest/vmad/vmad_state.cc, tools/daemon/bitmap.h, tools/daemon/hash.c, tools/daemon/message.c
These commits include set of test for daemon and fixes for observed issues.
=> issue: 1284081 Impove daemon verification

src/vma/util/utils.cpp, src/vma/util/utils.h
=> issue: 1308755 Traffic is not offloaded with NetVSC Alias interface

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.5.7 *******************

src/vma/lwip/tcp.c, src/vma/lwip/tcp_impl.h, src/vma/lwip/tcp_in.c, src/vma/proto/vma_lwip.cpp, src/vma/proto/vma_lwip.h
=> issue: 1190638 align lwip timer interval to VMA tcp timer interval

src/vma/lwip/tcp_in.c
TCP zero-window-probe should be sent as long as the window is full.
=> issue: 1262560 Fix zero-window ack probe

configure.ac, journal.txt
=> Issue: 321712 ****************** VMA 8.6.0 *******************

src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_udp.cpp, src/vma/sock/sockinfo_udp.h
=> issue: 1354251 Fix statistics for socketXreme income data

src/vma/sock/sockinfo_udp.cpp
Handle all the 3 possible data format given in this command.
Signed-off-by: Ariel Levkovich <lariel@mellanox.com>
=> issue: 1357010 Fix setsockopt(IP_MULTICAST_IF) with struct mreq

config/m4/nl.m4
=> issue: 1375982 Error message while libnl-route-3-dev is not installed

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.6.1 *******************

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.6.2 *******************

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.6.3 *******************

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.6.4 *******************

src/stats/stats_printer.cpp, src/stats/stats_reader.cpp, src/vma/dev/ring_simple.cpp, src/vma/util/vma_stats.h
This commit will enhance vma_stats -v 3 output to monitor also Tx
information about rings.
=> issue: 1382889 Add Tx statistics to ring

src/vma/dev/ring_simple.cpp, src/vma/sock/sockinfo.h, src/vma/sock/sockinfo_tcp.h, src/vma/sock/sockinfo_udp.cpp, src/vma/sock/sockinfo_udp.h
Disable the flow tag if setsockopt(SO_REUSEADDR) has been set
=> issue: 1338066 Fix disable flow tag for unicast flows

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.6.5 *******************

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.6.6 *******************

src/vma/dev/qp_mgr_eth_direct.cpp, src/vma/dev/qp_mgr_eth_direct.h, src/vma/dev/qp_mgr_eth_mlx5.cpp, src/vma/dev/qp_mgr_eth_mlx5.h
=> issue: 1403631 support master slave for qp direct

tools/daemon/notify.c
These changes allow to recognize zombie status of VMA process
and start cleanup procedure after it.
=> issue: 1402512 Daemon is able to detect VMA zombie process

src/vma/dev/ib_ctx_handler_collection.cpp, src/vma/dev/net_device_val.cpp, src/vma/util/utils.cpp, src/vma/util/utils.h
=> issue: 1416053 Fix valgrind invalid read warning

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.6.7 *******************

src/vma/sock/sockinfo.cpp
=> issue: 1417077 Fix TCP bind to device same interface failure

src/vma/dev/ib_ctx_handler_collection.cpp, src/vma/dev/net_device_val.cpp
=> issue: 1418379 Fix incorrect handling of IF_DOWN event

src/vma/dev/allocator.cpp
=> issue: 1365423 Fix fallback memory allocation logic

tools/daemon/flow.c
=> issue: 1428737 Add pending to remove list to daemon

src/vma/dev/cq_mgr.cpp, src/vma/dev/cq_mgr_mlx5.cpp, src/vma/dev/ring_simple.cpp
=> issue: 1178926 Support HW RX checksum in SocketXtreme

src/vma/dev/net_device_val.cpp
=> issue: 1431269 Fix bond ring with more than 2 resources error

src/stats/stats_reader.cpp, src/vma/dev/ring_slave.cpp, src/vma/util/vma_stats.h
=> issue: 1431683 Add retransmissions counter to ring_tap

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.6.8 *******************

src/vma/dev/ring_bond.cpp
=> issue: 1432927 Fix traffic stop after second fail over

src/vlogger/vlogger.h, src/vma/dev/allocator.cpp
=> issue: 1436435 Remove duplicate warning for not enough hugepages

README.txt, configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.6.9 *******************

tools/daemon/daemon.h, tools/daemon/flow.c
=> issue: 1452014 Fix gcc8 stringop-truncation warning

src/stats/stats_reader.cpp, src/vma/dev/rfs.cpp, src/vma/dev/rfs_mc.cpp, src/vma/dev/rfs_uc.cpp, src/vma/dev/ring_eth_cb.cpp, src/vma/dev/ring_eth_direct.cpp, src/vma/dev/ring_simple.cpp, src/vma/dev/ring_simple.h, src/vma/dev/ring_slave.cpp, src/vma/dev/ring_slave.h, src/vma/util/vma_stats.h
=> issue: 1450325 Enhance vma_stats output to monitor ring_type

src/vma/proto/dst_entry.cpp, src/vma/proto/dst_entry.h, src/vma/proto/dst_entry_udp_mc.cpp, src/vma/proto/dst_entry_udp_mc.h, src/vma/proto/header.cpp, src/vma/proto/header.h, src/vma/sock/sockinfo.cpp, src/vma/sock/sockinfo.h, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_tcp.h, src/vma/sock/sockinfo_udp.cpp, src/vma/sock/sockinfo_udp.h, src/vma/util/sysctl_reader.h
Set Time To Live (TTL) in the IP header
=> issue: 1322101 Add support for TTL

src/vma/iomux/epoll_wait_call.cpp, src/vma/sock/fd_collection.cpp, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_tcp.h, src/vma/util/vma_list.h
=> issue: 1469960 add iterator shortcut to vma_list_t

src/vma/sock/sockinfo_tcp.cpp
=> issue: 1480511 Fix TCP client hangs while connecting to local ip

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.7.0 *******************

config/m4/verbs.m4, src/vma/dev/cq_mgr.cpp, src/vma/dev/cq_mgr.h, src/vma/dev/dm_mgr.cpp, src/vma/dev/dm_mgr.h, src/vma/dev/ring_simple.cpp, src/vma/util/sys_vars.cpp, src/vma/util/sys_vars.h, src/vma/util/verbs_extra.cpp, src/vma/util/verbs_extra.h
=> issue: 1480982 Add cq_moderation support for upstream

src/vma/sock/sock-redirect.cpp, src/vma/sock/sock-redirect.h
=> issue: 1469556 Add sendfile support

src/vma/dev/ring_tap.cpp, src/vma/dev/ring_tap.h, tools/daemon/daemon.h, tools/daemon/flow.c, tools/daemon/message.c
These changes allow to use TCP/UDP connection on the same node
in case no SRIOV. This traffic goes through ring_tap.
Solution uses lo interface usage.
=> issue: 1417620 Enable UDP/TCP connection on same VM w/o SRIOV

src/vma/dev/net_device_val.cpp
=> issue: 1516726 Fix bond traffic not offloaded over IPoIB

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.7.1 *******************

contrib/valgrind/valgrind_vma.supp
=> issue: 1522890 Update valgrind suppression

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.7.2 *******************

src/vma/dev/ring_profile.cpp
=> issue: 1541768 Fix bad operator== in ring_profile

tools/daemon/daemon.c
=> issue: 1536822 Add Daemon version to help output

config/m4/verbs.m4, src/vma/dev/cq_mgr.cpp, src/vma/dev/ib_ctx_handler.cpp, src/vma/dev/ib_ctx_handler.h, src/vma/dev/time_converter.cpp, src/vma/dev/time_converter_ib_ctx.cpp, src/vma/ib/base/verbs_extra.h
Only for mlx5 and above devices.
=> issue: 1540484 Add UDP Rx Hardware timestamp support for upstream

src/vma/lwip/tcp.h, src/vma/lwip/tcp_impl.h
tcp_accept,tcp_recv,tcp_connect,tcp_listen,tcp_close.
=> issue: 1541702 Change the visibility of the global TCP names

src/vma/dev/ring_simple.h, src/vma/sock/sockinfo.cpp, src/vma/sock/sockinfo.h
Fix is due to CX3 change in VMA
=> issue: 1521601 Fix user defined flow tag

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.7.3 *******************

src/vma/ib/mlx5/ib_mlx5.h
=> issue: 1554167 Fix symbol lookup error for mlx5dv

src/vma/dev/allocator.cpp, src/vma/sock/sockinfo.cpp
=> issue: 1521396 Fix user memory passing to socket

src/vma/dev/ring_eth_cb.cpp
=> issue: 1521396 Reduce MP_RQ allocated size when stripping

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.7.4 *******************

src/vma/dev/net_device_val.cpp
=> issue: 1571899 Fix a typo in bond warning message

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.7.5 *******************

src/vma/dev/qp_mgr.cpp, src/vma/dev/ring_simple.cpp, src/vma/sock/sockinfo_udp.cpp
=> issue: 1566648 Fix missing initialization of poll_sn variable

contrib/valgrind/valgrind_vma.supp
Remove valgrind ignore for bug 1072426 memroy leak
=> issue: 1072426 Update valgrind suppression file

src/stats/stats_publisher.cpp, src/vma/event/event_handler_manager.cpp, src/vma/event/event_handler_manager.h
=> issue: 1583027 Fix crash in stats_data_reader::handle_timer_expired

src/vma/dev/net_device_val.cpp, src/vma/dev/net_device_val.h
Fix VMA ERROR related to mishandling of redirection map cleanup.
=> issue: 1537051 Fix VMA_RING_LIMIT_PER_INTERFACE VMA ERROR

contrib/valgrind/valgrind_vma.supp, src/vma/main.cpp, src/vma/sock/sockinfo_tcp.cpp
=> issue: 1073005 Fix memory leak for g_tcp_timers_collection

src/vma/sock/sockinfo.cpp, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_udp.cpp
=> issue: 1575056 Fix deadlock during TCP connection establishment

src/vma/iomux/epfd_info.cpp
=> issue: 1574908 Fix buffer overflow at epfd_info::statistics_print()

src/vma/dev/net_device_table_mgr.cpp, src/vma/dev/net_device_val.cpp, src/vma/dev/ring_bond.cpp
=> issue: 1600817 Resolve --enable-opt-log=high compilation errors

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.8.0 *******************

src/vma/dev/ring_eth_cb.cpp
=> issue: 1603531 Fix pad length in umr mode

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.8.1 *******************

src/vma/dev/qp_mgr.h, src/vma/proto/vma_lwip.cpp, src/vma/proto/vma_lwip.h
=> issue: 1608765 Clean vma_lwip class

README.txt, config/m4/verbs.m4, src/vma/dev/ib_ctx_handler.cpp, src/vma/dev/time_converter.cpp, src/vma/dev/time_converter_ptp.cpp, src/vma/dev/time_converter_ptp.h, src/vma/ib/base/verbs_extra.h
=> issue: 1592783 Add mlx5 PTP support for upstream

src/vma/dev/ib_ctx_handler.cpp, src/vma/dev/ib_ctx_handler.h, src/vma/dev/ib_ctx_handler_collection.cpp, src/vma/dev/ib_ctx_handler_collection.h, src/vma/dev/net_device_table_mgr.cpp, src/vma/dev/net_device_table_mgr.h, src/vma/dev/net_device_val.h, src/vma/dev/time_converter.cpp, src/vma/dev/time_converter.h, src/vma/sock/sockinfo.cpp
=> issue: 1576346 Modify RX HW timestamp capability calculation

src/vma/sock/sockinfo_tcp.cpp
=> issue: 825888 Fix incorrect TCP snd_wnd statistic

src/vma/dev/cq_mgr_mlx5.cpp
=> issue: 1646743 Fix get_cqe64() processing

src/vma/dev/ib_ctx_handler.cpp, src/vma/dev/net_device_val.cpp
=> issue: 1649370 Fix crash druing Plugin event

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.7.7 *******************

tools/daemon/flow.c
Filter node id selection for 3t-rules was based on the port value.
Hence, during migration, two TAP devices had the exact same rule.
This commit modifies this logic to match the 5t-rules logic.
=> issue: 1599446 Fix RX TAP migration failure for 3t connections

Makefile.am, build/libvma.spec.in, contrib/jenkins_tests/rpm.sh, contrib/jenkins_tests/tool.sh, contrib/scripts/vma.init.in, contrib/scripts/vma.service.in, debian/control, debian/copyright, debian/libvma.install, debian/postinst, debian/postrm, debian/prerm, debian/watch
This change should resolve conflict between SysV and SystemD to
vma service management/
=> issue: 1426871 Improve vma service support on different systems

src/vma/dev/ring_allocation_logic.cpp, src/vma/dev/ring_allocation_logic.h, src/vma/proto/dst_entry.cpp, src/vma/proto/dst_entry.h, src/vma/sock/sockinfo.cpp, src/vma/sock/sockinfo.h
=> issue: 1653789 Fix Rx/Tx migration thread safety

src/vlogger/vlogger.cpp, src/vlogger/vlogger.h, src/vma/dev/cq_mgr.cpp, src/vma/dev/cq_mgr.h, src/vma/dev/cq_mgr.inl, tools/daemon/daemon.c, tools/daemon/daemon.h
Decrease final binary size for 8%
=> issue: 1684500 Remove useless inline

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.8.2 *******************

src/vma/dev/cq_mgr_mlx5.cpp, src/vma/dev/cq_mgr_mlx5.h, src/vma/dev/cq_mgr_mp.cpp, src/vma/dev/cq_mgr_mp.h, src/vma/dev/ring_eth_cb.cpp, src/vma/dev/ring_simple.cpp
=> issue: 1663915 Fix destroy qp collision

src/vma/dev/net_device_table_mgr.cpp
This event usually skipped because all resources are released during
putting interface in DOWN state as a part of RTM_NEWLINK event.
It is valid in case there fast plugout when there is no RTM_NEWLINK(DOWN)
event.
=> issue: 1564149 Add RTM_DELLINK processing

src/utils/rdtsc.h
=> issue: 1732395 Detect CPU Frequency for aarch64

src/vma/dev/qp_mgr_eth_mlx5.cpp
=> issue: 1512054 Add warning in case Device Memory can not be used

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.8.3 *******************

src/vma/dev/ring_bond.cpp, src/vma/main.cpp, src/vma/sock/sockinfo_tcp.cpp
Most issues come from cppcheck 1.83
=> issue: 1734397 Fix csbuild 2.3.0 issues

src/vma/sock/sockinfo.cpp, tests/gtest/Makefile.am, tests/gtest/vma/vma_base.h, tests/gtest/vma/vma_sockopt.cc
Handle RING_LOGIC_PER_USER_ID unsupported optval provided to setsockopt and fail on.
=> issue: 1699062 Handle RING_LOGIC_PER_USER_ID unsupported optval

src/vma/sock/sockinfo_tcp.cpp
According accept() man description ECONNABORTED is expected
error value in case connection was aborted.
According getpeername() man description ENOTCONN is right value
for connections in not connected state.
These errors should be separated as far as getpeername() can be
called from both functions.
=> issue: 1797193 Return ECONNABORTED as error value for accept()

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.9.1 *******************

config/m4/verbs.m4, src/vma/sock/sock-redirect.cpp
=> issue: 1902084 Add deprecated message for Multi Packet RQ

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.9.3 *******************

src/vma/dev/cq_mgr_mp.cpp, src/vma/dev/cq_mgr_mp.h, src/vma/dev/qp_mgr_mp.h
=> issue: 1898614 Fix badhead tail access in mp_cq

src/vma/sock/sockinfo_tcp.cpp
These change improves return flow for nonblocking socket in case
operation can not send whole user buffer.
These changes include fix when blocking socket can return
partial data.
=> issue: 1930072 Fix send() operations processing

src/vma/dev/cq_mgr.cpp, src/vma/dev/cq_mgr.h, src/vma/dev/cq_mgr_mlx5.h, src/vma/dev/ring_simple.cpp, src/vma/dev/ring_simple.h, src/vma/ib/mlx5/ib_mlx5.h, src/vma/ib/mlx5/ib_mlx5_dv.cpp, src/vma/ib/mlx5/ib_mlx5_hw.cpp, src/vma/sock/sock-redirect.cpp, src/vma/vma_extra.h
=> issue: 1946579 Fix event notification logic used by extraAPI

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 8.9.5 *******************

contrib/valgrind/valgrind_vma.supp, src/vma/dev/time_converter.cpp, src/vma/event/event_handler_manager.cpp, src/vma/main.cpp, src/vma/proto/igmp_handler.cpp, src/vma/proto/neighbour.cpp, src/vma/sock/fd_collection.cpp, src/vma/sock/pipeinfo.cpp, src/vma/sock/socket_fd_api.h, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_tcp.h, src/vma/sock/sockinfo_udp.cpp
This PR includes some changes from https://github.com/Mellanox/libvma/pull/814
=> issue: 1775713 Fix sockinfo cleanup procedure

config/m4/dpcp.m4, config/m4/func.m4, config/m4/verbs.m4, configure.ac, src/vma/Makefile.am, src/vma/dev/ib_ctx_handler.cpp, src/vma/dev/ib_ctx_handler.h, src/vma/dev/net_device_val.cpp, src/vma/dev/qp_mgr_eth_direct.cpp, src/vma/dev/qp_mgr_eth_direct.h, src/vma/dev/ring_eth_direct.cpp, src/vma/dev/ring_eth_direct.h, src/vma/sock/sock-redirect.cpp, src/vma/vma_extra.h
It is based on https://github.com/Mellanox/libvma/pull/844
=> issue: 1971409 Add dpcp library support

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 9.0.1 *******************

Makefile.am, build/libvma.spec.in, configure.ac, debian/libvma-utils.install, debian/libvma.install, doc/man/Makefile.am, doc/man/vma.7.in, doc/man/vma_stats.8.in, doc/man/vmad.8.in
This PR is based on https://github.com/Mellanox/libvma/pull/412
=> issue: 928161 Add man pages

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 9.1.0 *******************

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 9.1.1 *******************

src/vma/dev/ring_slave.cpp
Issue happens when VMA is configured to use 3tuple (software rule).
This functionality is based on useing filter and counter value for
tracking open/close flows.
It should be handling under m_lock_ring_rx to avoid confilcts
during detach/attach flows with the same 3tuple (proto:dst_ip:dst_port).
=> issue: 1775713 Fix synchronization issue in attach/detach flow

configure.ac, journal.txt
=> issue: 321712 ****************** VMA 9.2.0 *******************

src/vma/dev/qp_mgr_eth_mlx5.cpp
The User Access Region (UAR) is a way to directly
access to the hardware registers. The mapping can be
performed with the type "Write-Combining" or "Non-Cached", and
these ones might be supported or not on different setups.
Current implementation is based on probing UAR allocation.
=> issue: 2355289 Improve check for BlueFlame support

README.md
=> issue: 2336287 Modify VMA official web page

src/vma/dev/ring_bond.cpp, src/vma/dev/ring_bond.h
These changes restore behaivour broken by
5723883 (issue: 1284069 Reduce m_active_rings usage from ring_bond)
=> issue: 2373738 Fix bonding 802.3ad transmission

src/vma/dev/ib_ctx_handler.cpp
VMA registers a timer per IB context which reads the card's clock during
clock synchronization. On IBV_EVENT_DEVICE_FATAL event we don't stop the
timer and attempt to read the clock leads to the SIGBUS.
In RoCE LAG mode we have a single IB device 'mlx5_bond_0', but after we
detach an interface from the bonding interface, the IB device disappears
and two separated devices are created instead: mlx5_0 and mlx5_1. At this
point original IB context becomes invalid and we receive IBV_EVENT_DEVICE_FATAL.
To mitigate the issue, destroy timer_converter on the event. Also, fix
duplicate timer_converter creation in the RoCE LAG mode where multiple
slaves point to the same IB context.
Signed-off-by: Dmytro Podgornyi <dmytrop@mellanox.com>
=> issue: 2380172 Resolve SIGBUS issue in RoCE LAG mode

src/vma/dev/cq_mgr.cpp, src/vma/dev/cq_mgr_mlx5.cpp
drain_and_proccess() is mainly called in following cases as
Internal thread:
Frequency of real polling can be controlled by
VMA_PROGRESS_ENGINE_INTERVAL and VMA_PROGRESS_ENGINE_WCE_MAX.
socketxtreme:
User does socketxtreme_poll()
Cleanup:
QP down logic to release rx buffers should force polling to do this.
Not null argument indicates one.
=> issue: 2130901 Fix issue in logic VMA_PROGRESS_ENGINE_WCE_MAX=0

tools/daemon/flow.c
=> issue: 2409546 Fix usage of memory after it is freed

src/vma/iomux/epfd_info.cpp
socket epoll context handling is risky area as far as there is no
common locks to protect synchronization between epoll and socket.
There is possible race between removal of fd from epoll (epoll_ctl(del), or epoll close)
and socket close().
This change removes socket epoll context as the first step. After this
socket does not have possibility to add events. As a result it is more
safety to clean socket references from epfd_info internal objects.
=> issue: 2580679 Fix handling socket close flow

CHANGES, configure.ac
=> issue: 321712 ****************** VMA 9.3.0 *******************

contrib/build_pkg.sh, contrib/jenkins_tests/rpm.sh, contrib/scripts/libvma.spec.in
=> issue: 2672690 Add dependencies check during package creation

.ci/Jenkinsfile, .ci/README.md, .ci/matrix_job.yaml, .ci/proj_jjb.yaml, Makefile.am, contrib/jenkins_tests/build.sh, contrib/jenkins_tests/commit.sh, contrib/jenkins_tests/compiler.sh, contrib/jenkins_tests/cov.sh, contrib/jenkins_tests/cppcheck.sh, contrib/jenkins_tests/csbuild.sh, contrib/jenkins_tests/globals.sh, contrib/jenkins_tests/gtest.sh, contrib/jenkins_tests/rpm.sh, contrib/jenkins_tests/style.sh, contrib/jenkins_tests/test.sh, contrib/jenkins_tests/tool.sh, contrib/jenkins_tests/vg.sh, contrib/jenkins_tests/vutil.sh, contrib/scripts/libvma.spec.in, contrib/test_jenkins.sh, debian/postinst, debian/postrm, debian/prerm
Add CI to K8
Move ci to ci-demo logic
To do CI more flexible
=> issue: 2583763 Add CI to K8

src/vma/dev/ib_ctx_handler.cpp, src/vma/lwip/tcp_in.c, src/vma/lwip/tcp_out.c, src/vma/main.cpp, src/vma/util/agent.cpp, src/vma/util/sys_vars.cpp, src/vma/util/sys_vars.h
Synchronization with XLIO 1.0.6
Submitted fixes from XLIO.
=> sync libxlio 1.0.6

CHANGES, configure.ac, contrib/scripts/libvma.spec.in
=> issue: 321712 ****************** VMA 9.4.0 *******************

.ci/matrix_job.yaml, contrib/jenkins_tests/cppcheck.sh, contrib/jenkins_tests/gtest.sh, contrib/jenkins_tests/test.sh, src/vma/sock/sock-redirect.cpp, tests/gtest/Makefile.am, tests/gtest/README, tests/gtest/common/base.cc, tests/gtest/tcp/tcp_base.cc, tests/gtest/tcp/tcp_base.h, tests/gtest/tcp/tcp_bind.cc, tests/gtest/tcp/tcp_send_zc.cc, tests/gtest/tcp/tcp_sendfile.cc, tests/gtest/tcp/tcp_tls.cc, tests/gtest/vma/vma_base.cc, tests/gtest/vma/vma_base.h, tests/gtest/vma/vma_poll.cc, tests/gtest/vma/vma_recvfrom_zcopy.cc, tests/gtest/vma/vma_ring.cc, tests/gtest/vma/vma_sockopt.cc
Modify CI content to be alligned with ci-demo.
CI configuration changes.
=> issue: 2583763 Update CI to align with ci-demo

CHANGES, configure.ac, contrib/scripts/libvma.spec.in
=> issue: 321712 ****************** VMA 9.5.0 *******************

.ci/matrix_job.yaml, config/m4/compiler.m4, src/stats/stats_reader.cpp, src/vma/util/sys_vars.cpp
Fix gcc12 compilation issue found by Fedora rawhide verification.
Fix gcc12 compilation issue. 
PR#2945718
=> issue: 2945718 Fix gcc12 compilation issue

.ci/matrix_job.yaml, contrib/jenkins_tests/cov.sh, contrib/jenkins_tests/csbuild.sh, contrib/jenkins_tests/globals.sh, contrib/jenkins_tests/rpm.sh
Set limit of threads to stable CI
=> issue: 2583763 Set limit of threads

.ci/matrix_job.yaml
=> issue: 2583763 Extend ci with ubuntu 22.04 

CHANGES, configure.ac, contrib/scripts/libvma.spec.in
=> issue: 321712 ****************** VMA 9.6.3 *******************

.ci/artifacts.sh, .ci/matrix_job.yaml
Signed-off-by: Vasily Ryabov <vryabov@nvidia.com>
Move duplicated code to single script.
=> issue: 3174914 Make job matrix more compact

debian/postinst
Skip postinst failure for containers.
=> issue: 321712 Prevent failure of debian postinst script

contrib/scripts/libvma.spec.in, debian/changelog.in, debian/control
Align maintatiner/changelog details with last requirements including reference to <networking-support@nvidia.com>.
=> issue: 3255476 Change package maintainer/changelog info

contrib/jenkins_tests/vg.sh
Valgrind stability, logs and error handling
Improve Valgrind stability.
Collect logs
Check for run errors.
Unstable CI
=> issue: 3249310 CI Valgrind stability and logs

CHANGES, configure.ac, contrib/scripts/libvma.spec.in
=> issue: 321712 ****************** VMA 9.7.2 *******************

.ci/matrix_job.yaml
Signed-off-by: Alexander Ryabov <aryabov@nvidia.com>
Added build in RHEL 8.6 and 9.0 containers, obsolete OS versions removed.
=> issue: 3325307 CI OS list updated

COPYING, contrib/jenkins_tests/copyright-check-map.yaml
Adding COPYING file for license
Missing file
Licensing
=> issue: 3336161 Adding COPYING license file

config/m4/compiler.m4
Fix compilation issue for gcc 13.0.1
Fix compilation
RM:3373882 
=> issue: 3373882 Fix compilation issue for gcc 13.0.1

contrib/jenkins_tests/cppcheck.sh, contrib/jenkins_tests/globals.sh, contrib/jenkins_tests/rpm.sh, contrib/jenkins_tests/test.sh, contrib/jenkins_tests/vg.sh, contrib/jenkins_tests/vutil.sh, contrib/test_jenkins.sh
Enable CI verification on CX5
Use ConnectX-5 in CI by default 
RM: 3497651
=> issue: 3497651 Use ConnectX-5 in CI by default

src/vma/dev/ring_allocation_logic.h, src/vma/sock/sockinfo.cpp
Fix corruption during ring release.
Fix XLIO_RING_MIGRATION_RATIO_RX=-1
RM:3615483
=> issue: 3615483 Fix corruption during ring release

contrib/jenkins_tests/gtest.sh, src/vma/lwip/opt.h, src/vma/lwip/tcp.c, src/vma/lwip/tcp.h, src/vma/sock/sockinfo_tcp.cpp, src/vma/util/sysctl_reader.h, src/vma/util/utils.cpp, tests/gtest/Makefile.am, tests/gtest/common/log.h, tests/gtest/tcp/tcp_sockopt.cc
Please provide a summary of the change.
_Subject: what this PR is doing in one line._ 
_Justification for the PR. If there is existing issue/bug please reference._
=> issue: 3655436 Add full TCP_KEEPALIVE support

README, src/vma/main.cpp, src/vma/sock/sock-redirect.cpp, src/vma/sock/sock-redirect.h, src/vma/sock/socket_fd_api.cpp, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_tcp.h, src/vma/util/sys_vars.cpp, src/vma/util/sys_vars.h
Porting 3697720 Fixes from https://github.com/Mellanox/libvma/commits/update/9.0.2/
=> issue: 3697720 Porting 9.0.21 Fixes

src/vma/event/delta_timer.cpp, src/vma/event/delta_timer.h, src/vma/util/utils.cpp, src/vma/util/utils.h
=> issue: 3749310 Fix main timer accuracy

contrib/jenkins_tests/rpm.sh, docs/man/vma.7.in, docs/man/vma_stats.8.in, docs/man/vmad.8.in
Issue: [HPCINFRA-920](https://jirasw.nvidia.com/browse/HPCINFRA-920)
Add private email scan in deb/rpm packages
Make sure we dont have any private emails in rom/deb packages information or changelog
RM3375239
=> Issue: 3375239 - add email scan in packages

.ci/redmine_jjb.yaml, .ci/redmine_matrix_job.yaml
Create JJB file for redmine checker, all CI should have code representation.
Migration of redmine checker pipeline to Blossom
Create JJB file for redmine checker with Blossom parameters
All CI should have code representation.
issue: 3977246
=> issue: 3977246 Migrate redmine checker pipeline to blossom

.ci/pipeline/release_jjb.yaml, .ci/pipeline/release_matrix_job_dr.yaml
Support for release process in DRP is required, since the envrironment is different than the prod environment there should be a new pipeline defined with said changes
Add new job template definition to release_jjb
Add new dr matrix with configuration for PDC env
Issue: HPCINFRA-1889
=> issue: 4007026 Disaster recovery pipeline

.ci/matrix_job.yaml, .ci/proj_jjb.yaml, .ci/scripts/doca_install.sh, contrib/jenkins_tests/rpm.sh
We're going to switch CI from MOFED driver to DOCA-host
Replace MOFED with DOCA
A part of MOFED->DOCA migration activities 
Update corresponding steps in CI, add installation script
=> issue 4042266: install DOCA-ofed instead of MOFED in CI

.ci/dockerfiles/Dockerfile.rhel8.6.release, .ci/pipeline/dr_weekly_matrix.yaml, .ci/pipeline/release_jjb.yaml, .ci/pipeline/release_matrix_job.yaml
Update webrepo URL to GeoDNS
Update webrepo URL to GeoDNS URL instead of geo-specific URLs in Prod and PDC sites
Unify URLs we us to simplify pipelines
=> [CI] issue: 4277240 Update webrepo URL to GeoDNS

contrib/jenkins_tests/cov.sh, src/stats/stats_reader.cpp, src/utils/lock_wrapper.h, src/vma/config_scanner.c, src/vma/dev/allocator.cpp, src/vma/dev/ring_allocation_logic.cpp, src/vma/dev/ring_simple.cpp, src/vma/dev/ring_tap.cpp, src/vma/event/delta_timer.cpp, src/vma/event/event_handler_manager.cpp, src/vma/event/event_handler_manager.h, src/vma/iomux/epfd_info.cpp, src/vma/lwip/tcp.c, src/vma/proto/dst_entry.cpp, src/vma/proto/igmp_mgr.cpp, src/vma/sock/fd_collection.cpp, src/vma/sock/sockinfo_udp.cpp, src/vma/util/sys_vars.h, src/vma/util/utils.cpp, tools/daemon/daemon.c, tools/daemon/flow.c, tools/daemon/notify.c
Coverity upgrade 2023.12 fixes
_Subject: what this PR is doing in one line._ 
_Justification for the PR. If there is existing issue/bug please reference._
=> Coverity upgrade 2023.12 fixes

.ci/proj_jjb.yaml, .ci/redmine_jjb.yaml
Move to media team dedicated service user
Shared user sometimes been abused by other teams causing GitHub token exhaustion
This causes delays in GHPRB plug in response
Issue: HPCINFRA-3449
=> [CI] Update GHPRB service user

SECURITY.md
Add SECURITY.md
Following SCM security hardening requirements public repos must contain security policies
=> [CI] issue HPCINFRA-3392 Add SECURITY.md
