Mellanox/libvma

README.txt, src/vma/main.cpp, src/vma/sock/sockinfo_tcp.cpp, src/vma/util/sys_vars.h
Add environment parameter VMA_INTERNAL_THREAD_TCP_TIMER_HANDLING
0 - deferred handling. The internal thread will not always handle TCP timer upon timer
expiration (once every 100ms) in order to let application threads handling it first if possible
1 - immediate handling. The internal thread will try locking and handle TCP timer upon
timer expiration (once every 100ms).
Default: 0 (deferred handling)
=> issue: 737508 Intenal thread TCP timer handling mode

src/vma/sock/sockinfo_tcp.cpp
This commit provides WA for the the issue:
rx_wait() call, that can cause to lost vma_poll() events,
is removed from the close lingering flow.
Signed-off-by: Alex Vainman <alexv@mellanox.com>
=> issue: 777422 fix socket close lingering that caused to vma events drops

src/vma/dev/cq_mgr.cpp, src/vma/dev/cq_mgr.h, src/vma/dev/ring.h, src/vma/dev/ring_simple.cpp, src/vma/dev/ring_simple.h, src/vma/proto/mem_buf_desc.h, src/vma/sock/sock-redirect.cpp, src/vma/sock/sockinfo_tcp.cpp, src/vma/vma_extra.h
The new API allows:
- Selective deallocation of the buffers provided by vma_poll().
- Decoupling between buffer management and "Transport Credits" (TCP WIN) update.
Signed-off-by: Alex Vainman <alexv@mellanox.com>
=> issue: 781407: vma_poll: add support for selective vma buffers deallocation API

autogen.sh, configure.ac, contrib/jenkins_tests/test.sh, contrib/test_jenkins.sh, src/state_machine/Makefile.am, src/stats/Makefile.am, src/vlogger/Makefile.am, src/vma/Makefile.am, src/vma/dev/wqe_send_handler.h, src/vma/dev/wqe_send_ib_handler.h, src/vma/infra/Makefile.am, src/vma/netlink/Makefile.am, src/vma/proto/header.h
This change disables usage of dependencies.
Current source code structure allows usage of the same source files/objects
in different libs/bins. So there is a case when .deps folder can be removed
but other component includes .Plo files that does not exists and it leads
to error.
Example:
Makefile can have 'include ../../vlogger/$(DEPDIR)/nl_test-vlogger.Po'
but vlogger/$(DEPDIR) was removed before
There is a possibility to reorganize build ordering and linking dependency
but it requires more changes.
=> issue: 775440 make distclean is broken

src/vma/sock/sockinfo_udp.cpp, tests/bindtodevice/client.py
commit includes a simple python test code which calls setsockopt(SO_BINDTODEVICE)
to test these changes
Update log example:
VMA DEBUG: ENTER: setsockopt(fd=21, level=1, optname=25)
VMA DEBUG: si_udp[fd=21]:808:setsockopt() SOL_SOCKET, SO_BINDTODEVICE='ens3' (4.4.4.12)
VMA DEBUG: EXIT: setsockopt() returned with 0
=> issue: 781384 add log details on UDP setsockopt(SO_BINDTODEVICE)

src/vma/dev/cq_mgr.cpp, src/vma/dev/ring.h, src/vma/dev/ring_simple.cpp, src/vma/dev/ring_simple.h, src/vma/proto/mem_buf_desc.h, src/vma/sock/sock-redirect.cpp
In order to reduce free_vma_buff() overhead vma_buff is not returned
by free_vma_buff() to CQ's rx buffer pool or to rx global buffer pool
but just inserted into pending for remove ring's list that is handled
on free_vma_packets() or on ring destruction.
=> issue: 784317: Implement optimized free_vma_buff()

src/vma/sock/sockinfo_tcp.cpp, src/vma/util/sys_vars.h
=> issue: 778287 Fix using safe_mce_sys() calls instead of direct usage of mce_sys struct

src/vma/sock/sockinfo.cpp, src/vma/sock/sockinfo.h, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_udp.cpp, src/vma/vma_extra.h
New VMA specific option allows to provide user defined data
in vma_completion_t as result of vma_poll().
By default socket descriptor is returned.
SO_VMA_USER_DATA option associated with SOL_SOCKET level.
=> issue 777416: Add SO_VMA_USER_DATA option for setsockopt()

config/m4/opt.m4, configure.ac, src/vlogger/vlogger.h, src/vma/dev/net_device_table_mgr.cpp, src/vma/dev/net_device_val.cpp, src/vma/dev/qp_mgr.cpp, src/vma/dev/ring_simple.cpp, src/vma/proto/dst_entry_tcp.cpp, src/vma/proto/neighbour.cpp, src/vma/sock/sock-redirect.cpp, src/vma/sock/sockinfo_tcp.cpp
These changes allow to exclude debug level logging from
binary. It does not impact panic, err, warn and info output.
In addition it disable/enable assert() calls.
It is controlled by --enable-opt-log configuration option (default off).
Motivation:
- this change is able to improve performance (for example: sockperf pp -m202 --tcp reports ~100-150ns benefit)
Note:
- if we need to ON this by default keeping in mind that it cuts off debug output more than INFO level.
=> issue: 775233 Add control for logging

src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_tcp.h, src/vma/vma_extra.h
This commit adds auto accept support for vma_poll():
- When connection on server side enters into established state
VMA generates VMA_POLL_NEW_CONNECTION_ACCEPTED event.
- EPOLLIN event is not reported for the listen socket.
- No need calling accept() but application can start immediately
getting packets from the new connection via vma_poll().
Signed-off-by: Alex Vainman <alexv@mellanox.com>
=> Issue: 777420 Add support for auto accept

src/vma/util/libvma.conf
Add to libvma.conf file: by default use OS for handling DNS server side
UDP port 53
=> issue: 804206 DNS server (UDP,port 53) to be handled by OS by default

src/vma/sock/sockinfo_tcp.cpp, src/vma/vma_extra.h
In addition to user_data and src address return parent/listen
socket fd number in auto accept event.
That allows application to locate for new accepted connection its listen socket.
Signed-off-by: Alex Vainman <alexv@mellanox.com>
=> issue: 816454 Return listen fd in auto accept event

src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_tcp.h
If TCP sndbuf is 0 we are dependent on incoming ACKs to increase sndbuf. In
non-blocking mode only the internal thread is currently responsible for
draining the CQ and processing this ACK. However, the internal thread
operates by default once every 10ms.
This feature adds the user application as source of polling the CQ
immediately as part of tx() operation.
This feature is only applicable in non-blocking mode
=> issue: 816006 In case tcp sndbuf is 0 - poll once CQ for an ACK (non-blocking rx)

src/vma/dev/qp_mgr.cpp
In case QP can not be created we need destroy qp_mgr object
safely.
@OphirMunk please review
=> issue: 823094 Fix bug in case QP unexpected failure

contrib/jenkins_tests/cov.sh, contrib/test_jenkins.sh
Added additional option for analyzes:
--enable-fnptr --fnptr-models - follows function pointers (by default it doesn't)
--all - add some checkers
--paths - increases number of paths checked (default is 5k, it increase cov run duration)
New options enable new issues that should be resolved in separate PR.
=> issue: 786406 Make coverity check stronger

README.txt, src/vma/dev/ib_ctx_handler.cpp, src/vma/dev/ib_ctx_handler.h, src/vma/dev/qp_mgr.cpp, src/vma/dev/qp_mgr.h, src/vma/main.cpp, src/vma/util/sys_vars.cpp, src/vma/util/sys_vars.h
Replace the hardcoded NUM_TX_POST_SEND_NOTIFY (64) with a load time
VMA configuration parameter: VMA_TX_WRE_BATCHING
By controlling the size of Tx list collected until request a completion
signal we can better control the jitter encountered from the Tx CQE handling.
Valid value range: 1-64
Default: 64 (like the hardcoded value before the chaneg)
=> issue: 828809 control the number of post sends until requesting SIGNAL

README.txt, src/vma/dev/cq_mgr.cpp, src/vma/dev/cq_mgr.h, src/vma/dev/ring_simple.cpp, src/vma/main.cpp, src/vma/proto/dst_entry_tcp.cpp, src/vma/proto/dst_entry_udp.cpp, src/vma/proto/igmp_handler.cpp, src/vma/proto/mem_buf_desc.h, src/vma/proto/neighbour.cpp, src/vma/util/sys_vars.cpp, src/vma/util/sys_vars.h, src/vma/util/utils.cpp, src/vma/util/utils.h, src/vma/util/verbs_extra.h
Support software checksum validation for receive IP and TCP/UDP packets.
Software checksum validation will be compute (if enabled) only if HW checksum validation failed.
Enable/Disable using VMA_RX_SW_CSUM parameter.
Enabled by default (should cause a performance degradation if HW checksum
validation is not supported).
=> issue: 822441 Support receive SW checksum

src/stats/stats_reader.cpp, src/vma/util/vma_stats.h
1. socket array starts at END OF sturct sh_mem_t. No addition member after it.
2. full key word wrongly used for '--fd_dump'
=> issue: 825888 small fixes for dump fd statistics

src/vma/infra/sender.h, src/vma/proto/neighbour.cpp, src/vma/proto/neighbour.h
(CLANG_WARNING) warning: Use of memory after it is freed
=> issue: 848172 Fix csbuild report errors in neighbor handling

src/vma/sock/sockinfo.cpp
Increment reference counter inside create_nd_resources.
We need to synchronize ref counters for objects in
m_rx_nd_map and m_rx_ring_map.
Now create_nd_resources/destroy_nd_resources are responsible
for updating ref counters for nd_resources and ring.
@OphirMunk please accept
=> issue: 870765 Update ref counter for allocated resources

README.txt, src/vma/sock/pipeinfo.cpp, src/vma/sock/socket_fd_api.cpp, src/vma/sock/socket_fd_api.h, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_udp.cpp
1. Enable OS socket read following a failed OS call with MSG_VMA_ZCOPY_FORCE
2. Remove MSG_VMA_ZCOPY bit flag when calling the OS
=> issue: 911076 Fix rcvmsg failure with MSG_VMA_ZCOPY_FORCE on OS socket

src/vma/dev/net_device_table_mgr.cpp, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_udp.cpp, tests/gtest/Makefile.am, tests/gtest/sock/sock_base.cc, tests/gtest/sock/sock_base.h, tests/gtest/sock/sock_socket.cc, tests/gtest/tcp/tcp_base.cc, tests/gtest/tcp/tcp_send.cc, tests/gtest/tcp/tcp_sendto.cc, tests/gtest/udp/udp_base.h, tests/gtest/udp/udp_bind.cc, tests/gtest/udp/udp_send.cc, tests/gtest/udp/udp_sendto.cc
These changes include
- invalid parameters check for UDP send/sendto/write/sendmsg functions
- new UDP test cases for gtest 
- fix such issues as 875728, 875722, 875716, 875715, 120924, 120922, 120920, 120784, 120753
=> issue: 1043830 Fix UDP sendto error processing

src/vma/lwip/opt.h, src/vma/lwip/tcp_in.c
TCP_QUICKACK_THRESHOLD parameter was added to lwip/opt.h
Change TCP_QUICKACK_THRESHOLD value in order to disable quickack for payloads
that are larger than the threshold.
By default, quickack threshold is disabled.
The threshold is effective only when TCP_QUICKACK is enabled.
=> issue: 1207424 Send quickack depending on the payload size

src/vma/dev/rfs.cpp, src/vma/dev/rfs.h
When unexpected closing occurs while there is an established TCP connection,
VMA can try to destroy ibv_flow from the RFS which did not create it.
Hence, during RFS destructor we need to update m_p_rule_filter's map in order
the destroy the correct flow.
=> issue: 1192017 Fix ibv_destroy_cq() failure while VMA_TCP_3T_RULES=1

src/vma/main.cpp
VMA should display warning just in case flow steering is disabled
in configuration.
As far as this capability is controlled by bits 0..5 and
b0 is responsible to flow steering force it is enough to check
single b0 bit.
=> issue: 1222660 Correct warning check for flow steering

src/vma/proto/neighbour.cpp, src/vma/proto/neighbour.h
ARP (short for "Address Resolution Protocol") is a network protocol used
to map an IP network address to a corresponding hardware MAC address.
When static ARP entries are added manually on locally cached ARP table,
there is no need to send out ARP requests.
=> issue: 1168028 Add support for static ARP entries

configure.ac
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
This date call only works with GNU date.
Signed-off-by: Bernhard M. Wiedemann <bwiedemann@suse.de>
Without this patch, building the libvma package on openSUSE Linux would always produce differing results with a diff like
```diff
/usr/share/doc/packages/libvma-8.4.8/VMA_VERSION        2017-11-14 12:00:00.000000000 +0000
@@ -1,4 +1,4 @@
VMA VERSION: 8.4.8-0
VMA SVN-REVISION: 8
-BUILD DATE: Nov/26/2017 08:02:24
+BUILD DATE: Jan/01/2019 21:18:51
```
=> issue: 1235810 Allow to override build date

src/vma/util/agent.cpp, tools/daemon/hash.c, tools/daemon/loop.c, tools/daemon/notify.c
Filesystem monitor selection should be based on libc ability
to support fanotify or inotify and kernel configuration.
=> issue: 1214453 Improve selection of filesystem monitor method

README.txt, src/vma/Makefile.am, src/vma/lwip/cc.h, src/vma/lwip/cc_none.c, src/vma/lwip/tcp.c, src/vma/proto/vma_lwip.h
While TCP congestion control algorithm is disabled, VMA will send data
as long as there is room in the advertised window.
Usage : VMA_TCP_CC_ALGO = 2.
For more details about Congestion Control Algorithms see RFC-2581.
=> issue: 1242606 Disable TCP congestion control using VMA parameter

src/vma/lwip/tcp_in.c
Extract lwip patch - An incoming RST should be ignored
=> issue: 1229443 Not respond to incoming RST

src/vma/dev/qp_mgr_eth_mlx5.cpp
Blue Flame register should be written using Write Combining, generating
bursts of one (or more) cache lines. If the WQE size is smaller than
(a multiple of) a cache line, the WQE written to the
Blue Flame buffer should be padded up to the closest cache line boundary.
=> issue: 1171143 Add write combining barrier for Blue Flame send

src/vma/Makefile.am
User who installs any application/library should be responsible
for library cache area update. Using this explicitly
during make install does not allow a user to control/manage
installation process.
At the same time there are different restricted environments,
such as Gentoo sandbox, that consider such call as violation.
=> issue: 1069965 Remove ldconfig from installation

src/vma/netlink/netlink_wrapper.cpp
In order to fix errors during netlink callback registrations at startup 
500usec delay was added between registration calls (commit ecc891f).
While this workaround worked in several scenarios a more appropriate solution
is to change the order of registrations such that neigh updates are registered last.
=> issue: 1250147 Reorder netlink event registration at startup

src/vma/proto/neighbour.cpp, src/vma/proto/neighbour.h
Wrong handling of INCOMPLETE neighbor state causes VMA to send
SYN packets to invalid peers.
=> issue: 1258245 Fix SYN messages are sent to invalid peer

src/vlogger/vlogger.h, src/vma/sock/sock-redirect.cpp, src/vma/vma_extra.h
VMA extra api struct is not initialized with unsupported functions.
For example, when socketXtreme was not enable during configuration time
and when Striding RQ is not supported,
This can cause the user application to crash.
This commit will avoid those crashes by set the errno to EOPNOTSUPP and
print a relevent warning message.
=> issue: 1262144 Print warning when extra api functions are not supported

src/vma/dev/qp_mgr_eth_direct.cpp
mlx5hw returns the wrong address for RAW_ETH_QP.
This fix update the right one form verb's data
=> issue: 1226478 fix SQ buf pointer

src/vma/dev/buffer_pool.cpp, src/vma/dev/buffer_pool.h, src/vma/dev/cq_mgr.cpp, src/vma/dev/cq_mgr.inl, src/vma/dev/qp_mgr.cpp, src/vma/dev/qp_mgr.h, src/vma/dev/ring_simple.cpp
During runtime, requesting buffers from the global buffer pool requires
double iteration over the buffers list, this should be optimize to a
single run.
=> issue: 1259552 Optimize global get buffers procedure

contrib/jenkins_tests/test.sh
As far as sockperf is compiled with VMA API by default actual
location to libvma should be set.
=> issue: 1172298 Compile sockperf for jenkins against actual libvma

contrib/scripts/vma.service.in
Upstream can be installed w/o openibd service. Remove one
from needed services for vma.service launch.
=> issue: 1264919 Improve vma.service unit for inbox

config/m4/nl.m4
You can compile libibverbs so it won't use libnl at all. In
those cases vma should pick any libnl that is installed.
=> issue: 1263120  fix compilation if libibverbs doesn't use libnl

config/m4/verbs.m4, src/vma/dev/qp_mgr.cpp, src/vma/dev/qp_mgr.h, src/vma/dev/ring.h, src/vma/dev/ring_bond.cpp, src/vma/dev/ring_bond.h, src/vma/dev/ring_simple.cpp, src/vma/dev/ring_simple.h, src/vma/proto/dst_entry.cpp, src/vma/proto/dst_entry.h, src/vma/proto/dst_entry_tcp.cpp, src/vma/proto/dst_entry_tcp.h, src/vma/proto/dst_entry_udp.cpp, src/vma/proto/dst_entry_udp.h, src/vma/sock/sockinfo.cpp, src/vma/sock/sockinfo.h, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_udp.cpp, src/vma/util/verbs_extra.cpp, src/vma/util/verbs_extra.h, src/vma/vma_extra.h
Enable configuring burst control by modify_qp. By using burst control
with rate limiting, the user can achieve best performance and accuracy.
If only one of the options is specified by the user between RATE_LIMIT
and BURST_INFO, mlx5 driver will use the saved value for the other field.
Signed-off-by: Ilan Smith <ilansm@mellanox.com>
=> issue: 1254846 Add support for packet packing burst control

src/vma/dev/rfs_uc_tcp_gro.cpp, src/vma/dev/ring.cpp, src/vma/dev/ring.h, src/vma/infra/sender.h, src/vma/proto/dst_entry.cpp, src/vma/proto/dst_entry.h, src/vma/proto/neighbour.cpp, src/vma/proto/neighbour.h, src/vma/proto/route_table_mgr.cpp, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_tcp.h, src/vma/sock/sockinfo_udp.cpp, src/vma/sock/sockinfo_udp.h
This commit adds support for IP_TOS attribute in setsockopt,
witch is written inside the IP TOS field.
VMA had a lack of usage in the tos when resolving the route
and used the route mtu in places it shouldn't had.
This commit adds the TOS and PCP and alignes all the tos
usage
=> issue: 1248968 Add sesockopt for IP_TOS

README.txt, install.sh
The recommended installation command which mentioned in README.txt
and install.sh should install all files the same location as
MLNX_OFED.
=> issue: 1277085 Update recommended installation command

src/vma/dev/ring_bond.cpp
Interface name length should not exceed IFNAMSIZ includes a
trailing null.
=> issue: 1279344 Fix gcc7 format-truncation warning

config/m4/verbs.m4, src/vma/dev/qp_mgr.cpp, src/vma/sock/sockinfo.cpp, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_udp.cpp, src/vma/util/verbs_extra.cpp, src/vma/vma_extra.h
The burst control was developed and introduced in a previous commit
while the feature was still under development in libibverbs.
The final version in libibverbs has some API changes which this change
accommodates for.
Signed-off-by: Ilan Smith <ilansm@mellanox.com>
=> issue: 1254846 Align burst control with libibverbs new API

src/vma/lwip/tcp_out.c
Added a fix to TCP split function - segment splitting logic in case of
a segment with data bigger than available window size.
This PR includes the following bug fixes:
1. Fix max new pbuf size.
2. Fix untreated pcb->last_unsent segment pointer update in case of
a pbuf smaller than available window size.
3. Fix wrong TCP header calculation.
4. Fix segment link list update order in case of a failure during new
segment allocation.
Signed-off-by: Daniel Libenson <danielli@mellanox.com>
=> issue: 1280902 Fix tcp_split_segment()

src/vma/dev/net_device_table_mgr.cpp, src/vma/dev/net_device_val.cpp, src/vma/dev/ring.h, src/vma/dev/ring_bond.cpp, src/vma/dev/ring_bond.h, src/vma/dev/ring_eth_cb.cpp, src/vma/dev/ring_eth_cb.h, src/vma/dev/ring_eth_direct.cpp, src/vma/dev/ring_eth_direct.h, src/vma/dev/ring_simple.cpp, src/vma/dev/ring_simple.h, src/vma/iomux/epfd_info.cpp, src/vma/sock/sockinfo.cpp, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_udp.cpp
wait_for_notification_and_process_element() and drain_and_proccess()
always call with CQT_RX.
=> issue: 1311399 Remove cq_type parameter from ring functions

src/vma/lwip/tcp_in.c
MSS TCP option field must only be sent in the initial
connection request.
i.e., in segments with the SYN control bit set.
Signed-off-by: Mohammad Al Khaldi <mohammadalk@mellanox.com>
=> issue: 1322084 Fix TCP MSS incompatibility with RFC-793

src/vma/sock/sockinfo.cpp, src/vma/sock/sockinfo.h, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_udp.cpp
The value for setting socket option SO_MAX_PACING_RATE is provided in
bytes.
For the enhanced version of this socket option (where we set rate,
burst size and packet size) the rate is provided in Kbps to prevent
an unnecessary double conversion and loss of accuracy.
=> issue: 1330652 Use kbps value for setting enhanced rate limit

src/vma/dev/ring_eth_cb.cpp
=> issue: 1332983 Add some debug prints to ring_cb

src/vma/dev/cq_mgr.h, src/vma/dev/ring_simple.h
This commit improves performance when converting CQE TS, instead of
using the CQ pointer to get the ib_ctx pointer we take the pointer
from the ring itself.
=> issue:1353974 use ib_ctx inside ring to convert CQE TS to timespec

src/vma/dev/cq_mgr.cpp, src/vma/sock/sockinfo_udp.cpp, src/vma/vma_extra.h
Adding HW timestamp reporting in the packet descriptor
which is returned to user.
Signed-off-by: Ariel Levkovich <lariel@mellanox.com>
=> issue: 1182150 Support HW RX timestamp in SocketXtreme

contrib/valgrind/valgrind_vma.supp, src/vma/dev/ring_eth_cb.cpp, src/vma/dev/ring_eth_cb.h, src/vma/dev/ring_eth_direct.cpp, src/vma/dev/ring_simple.cpp, src/vma/dev/ring_simple.h
ring_eth_direct, ring_eth_cb have own approaches for qp creation
and they should call special create_qp_mgr() methods after
virtual table is configured.
It requires to delay ring_simple::create_resources() call.
At the same time few fields of ring_simple should be initialized
before logic of ring_eth_direct, ring_eth_cb constructors start.
=> issue: 1398946 Fix issue with incorrect ring_eth_cb creation

src/vma/dev/net_device_table_mgr.cpp
get_net_dev_index should check for upper interfaces only for
NetVSC interfaces.
=> issue: 1405898 Fix get_net_device_val search method

src/vma/dev/rfs.h, src/vma/dev/ring_simple.cpp, src/vma/dev/ring_slave.h, src/vma/dev/ring_tap.cpp
As for UDP, from this release, ring can be share between several IPs.
hence, tcp-flow-map should be based also on dst_ip.
=> issue: 1404279 Fix TCP sockets of secondary IPs are not offloaded

src/vma/main.cpp
Restart mlx4_core modules should be done using "openibd restart"
and not using modprobe.
=> issue: 1413587 Modify warning while log_num_mgm_entry_size != -1

src/vma/dev/allocator.cpp, src/vma/dev/ring_simple.cpp, src/vma/sock/sockinfo_udp.cpp, src/vma/sock/sockinfo_udp.h, src/vma/util/agent.cpp, src/vma/util/sys_vars.cpp, src/vma/util/sys_vars.h
New changes allow to differentiate types of VMs and provide
specific code for them. Current code support just limited
number of VMs and x86_64 architecture.
=> issue: 1405041 Improve hypervisor type detection

src/vma/dev/ring_tap.cpp
- Update Tx statistics.
- Use writev in send_buffer().
- Enable software checksum for incoming data.
=> issue: 1413354 Add Ring tap enhancements

src/vma/dev/allocator.cpp, src/vma/dev/allocator.h
This commit replaces the huge page technique used by VMA
to allocte huge pages to mmap.
mmap allocation is cleaner and kernel handles it better when
calling madvise on that memory segment.
=> issue: 1365423 Use mmap to allocate huge pages

src/vma/dev/ring.h, src/vma/dev/ring_bond.cpp, src/vma/dev/ring_bond.h, src/vma/dev/ring_simple.cpp, src/vma/dev/ring_simple.h, src/vma/dev/ring_tap.cpp, src/vma/dev/ring_tap.h, src/vma/proto/dst_entry_tcp.cpp
dst_entry_tcp::get_buffer should release only the first buffer - even
if the next elment exists.
This commit partially reverts "issue: 1331577 Remove dead
code from_ring simple".
=> issue: 1403118 Fix incorrect release memory of TX buffers

src/vma/dev/net_device_table_mgr.cpp
In order to maintain backward compatibility, Exception should be thrown
only when there are offloadable devices.
=> issue: 1405641 Fix crash when m_net_device_map_index is empty

src/vma/dev/ring_bond.cpp, src/vma/dev/ring_bond.h
Max inline size should be based only on SRIOV rings.
=> issue: 1423819 Enable Blue Flame send for NetVSC interface

src/vma/util/sys_vars.cpp
Microsoft Hyper detection does not work without SRIOV while valgrind
is loaded (see third banner).
This will cause VMA to be load with contig pages - which will cause
a core dump.
=> issue: 1424602 Fix crash while valgrind is loaded without SRIOV

src/vma/dev/ib_ctx_handler.cpp, src/vma/dev/qp_mgr.cpp
There is unpredicatble duration between getting RTM_NEWLINK event
from netlink (about interface removing) and IBV_EVENT_DEVICE_FATAL
event from ib kernel. After getting IBV_EVENT_DEVICE_FATAL usual
logic can meet issue with calling ibv functions and different
incorrect flows can start.
=> issue: 1416963 Improve device removing in plugout case

README.txt, src/vma/main.cpp, src/vma/util/agent.cpp, src/vma/util/agent_def.h, src/vma/util/sys_vars.cpp, src/vma/util/sys_vars.h, tools/daemon/daemon.c, tools/daemon/loop.c, tools/daemon/notify.c
By dafault VMA writes the fd output files to the folder
/tmp/vma/, and daemon reds them from there.
Now user can change this folder location,
VMA should be run with VMA_VMAD_NOTIFY_DIR and
vmad should be run with --notify-dir.
default folder remains /tmp/vma/
=> issue: 1387232 Add vmad configurable notify dir

src/vma/util/sys_vars.cpp
MLX5_DEVICE_FATAL_CLEANUP tells ibv_destroy functions we
want to get success errno value in case of calling them
when the device was removed.
It is actual for OFED 4.x but planned to avoid such usage.
=> issue: 1284069 Set MLX5_DEVICE_FATAL_CLEANUP env for mlx5 device

README.txt, src/vma/dev/cq_mgr.cpp, src/vma/dev/cq_mgr.h, src/vma/main.cpp, src/vma/util/sys_vars.cpp, src/vma/util/sys_vars.h
Managing software checksum validation for ingress TCP/UDP IP packets
is helpless as far as VMA is able to fallback to SW check if HW possibility
is not detected. In addition SW check does performance degradation.
=> issue: 1178926 Remove VMA_RX_SW_CSUM control

src/vma/dev/ib_ctx_handler.cpp
Enhance ib_ctx handler debug information to include also
max_qp_wre and on_device_memory information.
=> issue: 1433896 Enhance ib_ctx handler debug information

src/vma/lwip/tcp.c, src/vma/lwip/tcp_out.c
Use tcp_keepalive() instead of tcp_zero_window_probe() to
probe for window update without sending any data (which
will force us to split the segment).
=> issue: 1435682 Fix incorrect TCP seqno after zero-wnd-probe

src/vma/util/agent_def.h
Path for temporary files used by daemon set by VMA process
in VMA_VMAD_NOTIFY_DIR environment variable and path passed
in --notify-dir should be absolutelly identical.
=> issue: 1387232 Fix issue with vmad default path mismatch

src/vma/dev/ring_tap.cpp
Attach process can spend time but process can be terminated in the
middle. So no needs in reporting warning.
=> issue: 1449421 Suppress warning in case flow attach is interrupted

src/vma/dev/net_device_val.cpp, src/vma/util/sys_vars.h, src/vma/util/utils.cpp, src/vma/util/utils.h
RiCE lag is not supported by VMA. while enabled, VMA should
print a relevant warning in addition to instructions of how
to disable it.
=> issue: 1178933 Print warning while RoCE lag is enabled

tools/daemon/daemon.h, tools/daemon/notify.c
Kernel resource destroying process require a time. As a result
flow steering can keep a data after process termination so
peer`s ACK on spoofying SYNC can not be visible for OS and
detected by daemon intranl flow.
Let do several attempt to make the capability stable.
=> issue: 1463833 Improve peer notification capability

src/vma/dev/buffer_pool.cpp, src/vma/dev/buffer_pool.h, src/vma/dev/ib_ctx_handler_collection.cpp, src/vma/dev/ib_ctx_handler_collection.h, src/vma/dev/net_device_table_mgr.cpp, src/vma/dev/net_device_val.cpp, src/vma/dev/net_device_val.h, src/vma/util/utils.cpp, src/vma/util/utils.h
There is no need to iterate over all existing IB devices because
all information is received by netlink.
Signed-off-by: Liran Oz <lirano@mellanox.com
=> issue: 1427833 Update ib_ctx collection table by parameter

src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_tcp.h, src/vma/util/sock_addr.h
The returned address is truncated if the buffer provided is too small.
in this case, addrlen will return a value greater than was supplied to
the call.
=> issue: 1475443 Fix getsockname/getpeername returned data

src/vma/proto/neighbour.cpp
Specific interface device can have several ip addresses. So
loopback recognition should be based on checking all ip that
relates the device.
=> issue: 1477680 Fix issue with loopback detection

src/vma/util/sys_vars.cpp
RDMAV_ALLOW_DISASSOC_DESTROY tells ibv_destroy functions we
want to get success errno value in case of calling them
when the device was removed.
=> issue: 1498320 Set RDMAV_ALLOW_DISASSOC_DESTROY env for upstream

src/vma/util/agent.cpp, tools/daemon/notify.c
During stressfull scenario when mass of sockets are opened/closed
daemon processes income message slower. Increasing wait timeout
during recieve of daemon`s answer allows to issues during
communication agent/daemon.
Another way: to avoid using blocking operations on agent side.
=> issue: 1491767 Inrease SO_RCVTIMEO for agent socket

contrib/jenkins_tests/cppcheck.sh, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_tcp.h, src/vma/util/agent.cpp, src/vma/util/agent.h
See issue: 768398 for peer notification capability (see PR: https://github.com/Mellanox/libvma/pull/270)
This changes allow to cache state update in case lost connection
with vma daemon and notify daemon about cached state after
establishing connection.
Agent is able to detect connection lost and attemp to set it
again. After setting connection Agent send information about
TCP sockets state to daemon.
Signed-off-by: Igor Ivanov <igori@mellanox.com>
=> issue: 915305 Add connection with daemon on the fly

src/vma/dev/ib_ctx_handler_collection.cpp, src/vma/dev/net_device_val.cpp
Mlx modules are not started on upstream over Windows Hypervisor VMs
after reboot when SRIOV is disabled.
It this case, ibv_get_device_list() will return with an error.
This case is valid for Windows Hypervisor VM's because the modules
will be started automatically during the plugin procedure.
=> issue: 1536838 Enable plugin on upstream after reboot without SRIOV

src/vma/dev/cq_mgr.cpp, src/vma/dev/cq_mgr.h, src/vma/dev/qp_mgr.cpp, src/vma/dev/qp_mgr.h
Following a bug on upstream-driver VMs over Windows Hypervisor
for mlx4 devices, creation of CQ with size > 8192 is not supported.
This commits avoid this crash by reducing the size of CQ to 8192.
=> issue: 1498311 Fix crash during CQ creation on upstream

config/m4/verbs.m4, src/vma/ib/base/verbs_extra.cpp, src/vma/ib/base/verbs_extra.h
This feature enables a substantial reduction of deep
packet inspection during RFS dispatch.
Supported for mlx5 (and above) devices.
=> issue: 1540483 Add flow tag support for upstream

src/vma/dev/qp_mgr_eth_mlx5.cpp, src/vma/dev/qp_mgr_eth_mlx5.h, src/vma/dev/ring_simple.cpp, src/vma/dev/ring_simple.h
This change includes fix for ilegal instruction failure.
=> issue: 1512054 Enable direct mlx5 processing on VMs

tools/daemon/daemon.h
FID_MAX default value is increased to provide better out of box
solution. End user has a way to configure daemon for his application
using --fid command line option.
64K default value seems fine as far as there is C10k problem.
=> issue: 1513181 Increased FID_MAX for daemon

src/vma/sock/sockinfo.cpp
This change will prevent error print when using this ioctl
when VMA_EXCEPTION_HANDLING=2.
=> issue: 1552382 Redirect ioctl SIOCGIFVLAN

src/vma/dev/cq_mgr.cpp, src/vma/dev/qp_mgr.cpp, src/vma/dev/ring_tap.cpp
During intensive outgoing traffic it is possible that
number of free buffers are empty and as a result tx pool
can not give new buffer. Error processing in this case
missed unlock.
=> issue: 1523707 Fix deadlock collision for ring_tap

contrib/valgrind/valgrind_vma.supp
Remove valgrind ignore for issue 1072998 memory leak in tcp event
timer from suppressions file
=> issue: 1072998 memory leak in tcp event timer

src/vma/dev/cq_mgr_mlx5.cpp
Sanity check for cq: initialization of tx and rx cq
has difference
tx - is done in qp_mgr::configure()
rx - is done in qp_mgr::up()
as a result rx cq can be created but not initialized
=> issue: 1556067 Add sanity check in clean_cq()

src/vma/ib/mlx5/ib_mlx5.cpp
Initialization of cq can be done once to protect
internal data from corruption.
cq field is used to detect one time initialization
For example: this function can be called when QP is moved
from ERROR state to RESET so cq_ci or cq_sn should not be
updated.
=> issue: 1557786 Protect vma_ib_mlx5_get_cq()

src/vma/dev/ib_ctx_handler_collection.cpp, src/vma/dev/net_device_val.cpp
VMA will offload a NetVSC device (Windows Hyper-V network driver)
only if SRIOV is enabled at the initialization time.
=> issue: 1554637 Modify NetVSC device detection

src/vma/dev/ib_ctx_handler.cpp, src/vma/dev/time_converter.cpp, src/vma/dev/time_converter.h, src/vma/dev/time_converter_ib_ctx.cpp, src/vma/dev/time_converter_ib_ctx.h, src/vma/dev/time_converter_ptp.cpp, src/vma/dev/time_converter_ptp.h, src/vma/event/event_handler_manager.h
Time converter object was destroyed during plugout without cleaning
it from the internal thread's timer list.
=> issue: 1557681 Fix timer converter Segmentation fault

src/vma/dev/net_device_val.cpp, src/vma/util/sys_vars.h, src/vma/util/utils.cpp, src/vma/util/utils.h
RoCE lag is not supported by VMA. while enabled, VMA should
print a relevant warning and refer the user to the Release Notes.
=> issue: 1540213 Print warning while mlx4 RoCE lag is enabled

src/vma/sock/sockinfo_tcp.cpp
IP_TTL value should be inherited from the listen socket.
=> issue: 1564259 Fix IP_TTL socket option inheritance

src/vma/dev/qp_mgr.cpp, src/vma/event/event_handler_manager.cpp, src/vma/event/event_handler_manager.h
As part of the plugout process, the internal thread is responsible
for releasing the memory. At this time, no one is listening for
ibverbs events.
=> issue: 1557668 Fix infinite polling loop during plugout

src/vma/dev/cq_mgr.cpp, src/vma/dev/qp_mgr.cpp
Bug:
qp_mgr->down() and del_qp_rx() for RX CQ that reinitializes m_qp_rec
that is used during ~qp_mgr() inside clean_cq() for RX CQ.
=> issue: 1566916 Fix CQ cleanup ordering issue

src/vma/event/event_handler_manager.cpp
ibv_get_async_event() may fail with Bad file descriptor during plugout
No need to print an error in this case.
=> issue: 1571657 Suppress failure error of ibv_get_async_event

src/vma/config_parser.c, src/vma/sock/sock-redirect.cpp, src/vma/util/libvma.h, src/vma/vma_extra.h
Modify config_line input parameter of add_conf_rule() to
const char * instead of char *.
=> issue: 1575618 Modify add_conf_rule() input param type

src/vma/sock/sockinfo_tcp.cpp
Make triggered EPOLL events for RST packet same as kernel
=> issue: 1580794 Fix EPOLL events for RST packet

src/vma/dev/qp_mgr_mp.cpp
vlan should be part of the network header
=> issue: 1584343 Disable vlan stripping in MP_RQ

build/libvma.spec.in, debian/postinst
Installations can be in changeroots, in an installer context, or
in other situations where you don't want the services started.
Like the debian package the RPM package is not started by default
after installation, you have to do this manually by entering
the following commands as
- systemD:
systemctl enable vma
systemctl start vma
- systemV
service vma start
=> issue: 1435293 Do not start daemon during package installation

config/m4/verbs.m4, src/vma/dev/qp_mgr.cpp, src/vma/dev/qp_mgr_eth_mlx5.cpp, src/vma/ib/base/verbs_extra.h
This feature adds a new VMA extra API allowing applications to call
a dummy send flow which will warm up the CPU caches on the send fast path.
See User Manual for more info.
=> issue: 1592040 Add mlx5 Dummy-send support for upstream

src/vma/event/event_handler_manager.cpp, src/vma/sock/sock-redirect.cpp, src/vma/sock/sock-redirect.h
This commit fixes a problem that caused VMA to ignore SIGINT during
epoll_wait() while VMA_SELECT_POLL=-1 is used.
=> issue: 1522964 Fix epoll_wait() can't be interrupted

src/vma/dev/ring_tap.cpp, src/vma/util/utils.cpp
No need to abort tap creation while pclose() is falied
with ECHILD errno.
=> issue: 1614459 Suppress pclose() error for ring_tap

src/vma/dev/ib_ctx_handler.cpp, src/vma/dev/ib_ctx_handler.h, src/vma/dev/net_device_val.cpp, src/vma/dev/qp_mgr.cpp, src/vma/dev/qp_mgr.h, src/vma/dev/ring.h, src/vma/dev/ring_bond.cpp, src/vma/dev/ring_bond.h, src/vma/dev/ring_simple.cpp, src/vma/dev/ring_simple.h, src/vma/dev/ring_tap.h, src/vma/ib/base/verbs_extra.cpp, src/vma/ib/base/verbs_extra.h, src/vma/sock/sockinfo.cpp
Packet Pacing should be calculated once for each device and not during
QP creation.
=> issue: 1647737 Modify Packet Pacing capability calculation

src/vma/dev/ring_simple.cpp, src/vma/vma_extra.h
legacy VMA reports about packet pacing capability and not on burst
capability.
=> issue: 1651457 Add burst capabilty check to get_ring_descriptors

src/vma/sock/sockinfo_tcp.cpp
Current implementation prints debug message while tcp-timers are not
cleaned instead of cleaning them.
=> issue: 1073005 Fix g_tcp_timers_collection destructor cleanup

src/vma/dev/net_device_val.cpp
While RoCE lag is enabled, only single port has IB device.
Legacy VMA did not print RoCE lag warning while active slave did
not have IB device.
=> issue: 1668925 Fix RoCE lag warning is not presented

src/vma/dev/ib_ctx_handler.cpp, src/vma/dev/ib_ctx_handler.h, src/vma/dev/ib_ctx_handler_collection.cpp, src/vma/dev/net_device_val.cpp, src/vma/dev/qp_mgr.cpp, src/vma/main.cpp
VMA provides a warning while mlx4-steering-rules are disabled.
This warning is presented during main initialization even when no mlx4
devices are available and no socket-api functions were used.
=> issue: 1670999 Print mlx4 steering warning in ib_ctx_handler_collection

src/vma/sock/sock-redirect.cpp, src/vma/vma_extra.h
This adds additional mask to the extra API header so the user would
be able to query which methods were initialized by VMA as part of
vma_get_api().
=> issue: 1677457 Add methods mask to VMA extra api

src/vma/dev/cq_mgr.cpp, src/vma/dev/cq_mgr.h, src/vma/dev/cq_mgr_mlx5.h, src/vma/ib/mlx5/ib_mlx5.h, src/vma/ib/mlx5/ib_mlx5_dv.cpp, src/vma/ib/mlx5/ib_mlx5_hw.cpp
CQ consumer index should be updated before calling
ibv_ack_cq_events.
This only affects mlx5dv CQs.
=> issue: 1679709 Fix missing update of CQ consumer index

src/vma/sock/sock-redirect.cpp, src/vma/sock/sockinfo.cpp
un-offloading the socket from the socket context is not allowed.
=> issue: 1087459 Fix VMA_EXCEPTION_HANDLING=0/1 generates core

src/vma/sock/sockinfo.cpp, src/vma/sock/sockinfo.h, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_udp.cpp
Ignore events of a closed socket for SocketXtreme scenario.
=> issue: 1380243 Ignore events of a closed socket for SocketXtreme scenario

src/vma/main.cpp
g_stats_file should be set to null during free library resources
procedure.
=> issue: 1682300 Fix double free in free_libvma_resources

src/vma/sock/sockinfo_tcp.cpp
Deletion of TCP timer should be protected under socket lock in
This deletion is called from two different locations:
sockinfo_tcp::clean_obj - from the internal thread context.
sockinfo_tcp::err_lwip_cb - from the application thread.
=> issue: 1687458 Fix double free of TCP timer event

src/vma/dev/ib_ctx_handler_collection.cpp
These changes detect if mlx4_core module is build in kernel and
report debug output in this case. When mlx4_core is separate
module detailed warning is reported.
=> issue: 1701456 Enable mlx4 flow steering warning for VM

src/vma/main.cpp
This change allows to destroy g_p_agent in right order.
=> issue: 1798908 Fix daemon agent initialization in case fork() usage

src/vma/dev/net_device_table_mgr.cpp, src/vma/dev/ring_bond.cpp, src/vma/dev/ring_simple.cpp, src/vma/iomux/epfd_info.cpp, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_tcp.h, src/vma/sock/sockinfo_udp.cpp
Convert EBUSY internal errno to EAGAIN.
Few customers report EBUSY errno in case recv() is called on non-blocked socket.
Probably EAGAIN or EWOULDBLOCK is better to return according
man http://man7.org/linux/man-pages/man2/recvmsg.2.html
Formally EBUSY can be returned on any socket api but in fact socket application
does not know how to react on this.
=> issue: 1772805 Fix return code for non blocking recv()

contrib/valgrind/valgrind_vma.supp, src/vma/dev/cq_mgr_mlx5.cpp, src/vma/dev/ib_ctx_handler.cpp, src/vma/dev/qp_mgr.cpp, src/vma/ib/mlx5/ib_mlx5.cpp, src/vma/ib/mlx5/ib_mlx5_hw.cpp
This commit updates the ignore file and adds macros
to remove false positive errors when running vma with
debug log verbosity.
=> issue: 1718617 Update valgrind suppression file

src/vma/dev/qp_mgr_eth_mlx5.cpp
Observed issue on KVM systems for Westmere related sse instruction
usage to achieve better performance using BF.
It can be considered as optimal from bad ways as far as performance
mostly critical for bare metal systems.
=> issue: 1894523 Disable BF usage under VMs

src/vma/dev/cq_mgr.inl, src/vma/dev/rfs.h, src/vma/dev/ring_slave.cpp, src/vma/ib/base/verbs_extra.cpp, src/vma/proto/header.h, src/vma/proto/igmp_handler.h
gcc 9.x enables [-Werror=address-of-packed-member] verification.
So it produced taking address of packed member of <struct name>
may result in an unaligned pointer value.
=> issue: 1909532 Resolve gcc 9.x issues

src/vma/sock/sockinfo.cpp, src/vma/sock/sockinfo.h, src/vma/vma_extra.h
Add new VMA socket option that closes the RX side of the socket.
This is needed to avoid steering rules creation for TX ONLY sockets.
Adding steering entries in this case hurts performance, especially for big scale cases.
=> issue: 2016629 Add setsockopt to shutdown socket's RX side

src/vma/lwip/tcp.h, src/vma/lwip/tcp_out.c, src/vma/proto/vma_lwip.cpp, src/vma/proto/vma_lwip.h, src/vma/sock/pipeinfo.cpp, src/vma/sock/pipeinfo.h, src/vma/sock/sock-redirect.cpp, src/vma/sock/socket_fd_api.h, src/vma/sock/sockinfo.h, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_tcp.h, src/vma/sock/sockinfo_udp.cpp, src/vma/sock/sockinfo_udp.h
These changes improve performance of sendfile()/sendfile64() operations for TCP sockets eliminating extra copies.
=> issue: 1606044 Optimize Send File performance

src/vma/dev/qp_mgr_eth_mlx5.cpp
A SIGSEGV is an error(signal) caused during COPY_64B_NT in
case m_db_method == MLX5_DB_METHOD_BF.
=> issue: 2069198 Disable BF usage for Azure

src/vma/lwip/tcp_out.c
Avoid 1,2 phases in tcp_write() function in case TCP_WRITE_FILE
flag is set. Both phases uses memcopy that should not be done
in this case for current implementation.
In fact memcpy can be replaced with sys_read() operation in
considered flow but gain is not expected.
=> issue: 2076916 Fix sendfile() processing in lwip

src/vma/lwip/tcp_in.c, src/vma/lwip/tcp_out.c
When tcp_output() sends the last segment it leaves pcb->last_unsent
outdated. It can happen that last_unsent points to a freed segment
which is the last segment in the free list. In turn, it means that
last_unsent->next is NULL.
TCP code doesn't rely on validity of pcb->last_unsent pointer and
updates it every time it doesn't meet certain conditions. And the
pointer is NOT updated when pcb->last_unsent->next is NULL.
Therefore, in the above scenario, a freed segment can be updated
as the last unsent segment what corrupts the free list.
To resolve the issue, keep pcb->last_unsent pointer valid. It also
avoids segfault or wrong result in tcp_is_wnd_available().
As further step, the redundant code which updates pcb->last_unsent
can be removed.
Signed-off-by: Dmytro Podgornyi …
=> issue: 1928915 Keep pcb->last_unsent valid

src/vma/sock/sock-redirect.cpp, src/vma/sock/sockinfo_udp.cpp, tests/gtest/Makefile.am, tests/gtest/common/cmn.h, tests/gtest/common/sys.cc, tests/gtest/udp/udp_connect.cc, tests/gtest/udp/udp_sendto.cc, tests/gtest/vmad/vmad_hash.cc
New tests are added to check a scenario when
udp socket try to do unicast send using zero destination port.
=> issue: 2136324 Refuse sendto() operation to zero port

config/m4/dpcp.m4, configure.ac
1. If user attempts to enable dpcp in OFED with MLNX_LIBS configuration
he should see recommendation to use OFED with UPSTREAM_LIBS configuration.
2. Report error in case dpcp is not installed but user set --with-dpcp
=> issue: 2181872 Modify --with-dpcp configuration option

README.txt, src/vma/dev/net_device_val.cpp, src/vma/util/sys_vars.h, src/vma/util/utils.cpp, src/vma/util/utils.h
rdma-core stack does not use capability to force root privileges
during raw qp creation.
So it means that user should not be confused non workable advice.
=> issue: 2234519 Remove disable_raw_qp_enforcement option for rdma-core

src/vma/dev/allocator.cpp, src/vma/util/utils.cpp, src/vma/util/utils.h
These changes allow dynamically discover the huge page size,
knowing that some systems have different sizes 2M,4M,1G etc.
It can look at /proc/meminfo:   cat /proc/meminfo | grep Hugepagesize to get
the current pagesize for use with mmap()/munmap() if MAP_HUGETLB is to be used.
=> issue: 2233349 Detect default hugepage size

src/vma/lwip/tcp.c, src/vma/lwip/tcp_out.c
tcp_enqueue_flags() adds a segment to the tail on the unsent list, but
doesn't update last_unsent pointer. Fix this, because we have to keep
the pointer valid. Commit fe29e92 is related to this issue.
=> issue: 2239872 Keep last_unsent valid when enqueue flags

src/vma/dev/ib_ctx_handler.cpp
So far DevX doesn't support GPU memory registration so to use ibv_reg_mr
in DPCP it should have struct ibv_pd*. set_pd method was extended for
optional second parameter with ibv_pd* which was set in VMA.
Signed-off-by: Oleg Kuporosov <olegk@mellanox.com>
=> Issue: 2269696 Provide ibv_pd for DPCP adapter

configure.ac, src/utils/asm-x86.h, src/vma/dev/net_device_val.cpp, src/vma/sock/cleanable_obj.h, src/vma/util/utils.cpp
1. The register storage class specifier is deprecated in C++11
2. Disable -Wno-free-nonheap-object diagnostic that looks as
incorrect for gcc-11
=> issue: 2398382 Fix issues for gcc-11

src/vma/event/event_handler_manager.cpp
1. Call do_wakeup() only when the m_reg_action_q is empty to reduce number of epoll_ctl() syscalls.
2. Move do_wakup() under the lock to fix a race.
=> issue: 2259568 Reduce number of do_wakeup() for event_handler_manager and fix a race

src/vma/dev/ring_bond.cpp
This issue is appeared under Azure down/up interface scearion.
=> issue: 2668320 Fix m_p_n_rx_channel_fds update on bond ring restart

src/vma/sock/sockinfo_tcp.cpp, tests/gtest/Makefile.am, tests/gtest/vma/vma_recvfrom_zcopy.cc
Fixed incorrect drop of memory desc sequence to separate memory desc.
As a result vma_free_packets() return just single memory desc instead of
sequence.
=> issue: 1714768 Fix issue in vma_recvfrom_zcopy()

src/vma/dev/net_device_val.cpp, src/vma/sock/sockinfo.cpp
This change can be considered as an addition to previous
commit as (b4b9d7a)
issue: 559317 Continue processing CQ for ready FD after failure on one of them
Suppress not needed error
RM: #2822230
=> issue: 2822230 Suppress unwanted error when cq fd is removed

config/m4/dpcp.m4, src/vma/util/vma_list.h
C++17 has deprecated a few components that had been in C++ since its beginning,
and std::iterator is one of them.
Fix gcc12 compilation issue on Fedora36.
Change `std::iterator` usage
RM#2945718
=> issue: 2945718 Fix gcc12 compilation issue

src/vma/dev/ring_slave.cpp
Fixing UDP UC 3T/5T rules configuration
Fixing usage of tcp_3t config instead of udp_3t config. 
For UDP UC 'connected' socket the 3T/5T rules may be switched.
=> issue: 2789483 VMA_UDP_3T_RULES flag is not taken into account correctly for UDP UC

src/vma/dev/ring_bond.cpp, src/vma/dev/ring_tap.cpp
Issue happens when during switching sriov to off on established
connection.
Details: m_recv_rings is not updated because of slaves array
becames zero.
RM: 3045735
=> issue: 3045735 Fix no traffic during disabled sriov (azure)

src/vma/dev/rfs_uc.cpp
When run libvma over IPoIB device, access the `attach_flow_data_eth`
will trigger segment issue, as it is NULL.
Signed-off-by: Honggang LI <honggangli@163.com>
```bash
$ ./configure --enable-opt-log=none
$ VMA_TRACELEVEL=6 LD_PRELOAD=./src/vma/.libs/libvma.so ~/udp/server.exe 7777
......
Pid: 214208 Tid: 214213 VMA FINER: ndtm[0x18a6e20]:525:global_ring_drain_and_procces() ret_total=0
Pid: 214208 Tid: 214213 VMA FINER: ndtm[0x18a6e20]:532:global_ring_adapt_cq_moderation() 
Pid: 214208 Tid: 214213 VMA FINER: ndv[0x18a7ef0]:1201:ring_adapt_cq_moderation() 
Pid: 214208 Tid: 214213 VMA FINER: evh:937:thread_loop() calling orig_os_api.epoll with 10 msec timeout
Pid: 214208 Tid: 214208 VMA DEBUG: ring_slave[0x1982be0]:179:attach_flow() flow: dst:192.168.6.67:7777, src:0.0.0.0:0, proto:UDP, …
```
=> Fix segment fault issue

src/vma/sock/sock-redirect.cpp
The signal() API does not take into consideration the VMA_HANDLE_SIGINTR env flag.
Make signal() to consider VMA_HANDLE_SIGINTR.
Currently, there is no way to disable VMA SIGINT overtake.
=> issue: 3092554 Use VMA_HANDLE_SIGINTR for signal() API

src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_tcp.h, tests/gtest/common/base.cc, tests/gtest/common/base.h, tests/gtest/common/sys.cc, tests/gtest/tcp/tcp_base.cc, tests/gtest/tcp/tcp_base.h, tests/gtest/tcp/tcp_connect.cc
When a blocking connect() returns with an error, it may already start a timer. So in case the internal threads tries to rto the SYN a segmentation fault occurs. 
Timer should not be started for failed blocking connect()
Reproductive gtests added.
Fixing segmentation fault.
Start timer only for non-blocking socket connect() or successful connect() of a blocking socket.
=> issue: 3092555 Fixing blocking socket connect timer race

src/vma/sock/sockinfo_tcp.cpp
Fix #992. `m_conn_state` value is overwritten before it's used in a condition.
Fix #992.
Bugfix
=> issue: 3092555 Fix connect timeout return value

src/vma/sock/sockinfo_tcp.cpp, tests/gtest/tcp/tcp_connect.cc
Fixing issue of no SYN rexmit due to previous timer change.
Refactoring the solution.
Continuation for PR 992.
Fixing no SYN rexmits + refactoring.
=> issue: 3092555 Cont for PR992: Blocking socket connect race

src/vma/proto/dst_entry_udp.cpp, src/vma/proto/dst_entry_udp.h, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_udp.cpp, src/vma/util/utils.cpp, tests/gtest/common/base.cc, tests/gtest/common/base.h, tests/gtest/tcp/tcp_send.cc, tests/gtest/udp/udp_send.cc
VMA passes tx to OS in case the one element of the iov vector is null. Thus, breaking the connection.
Skip null elements in iov vector but process those that are not null.
1. It is not forbidden to have null element in the iov vector. 
2. Kernel handles that well. 
3. Couchbase server behaves like this.
=> issue: 3173318 Fixing the handling of null elements in iov tx vector.

Makefile.am, contrib/jenkins_tests/tool.sh, contrib/scripts/libvma.spec.in, debian/postinst, debian/prerm
vma service setup/removal
Support only systemctl. Remove obsolete registration/deregistration methods.
Compatibility with new systems and containers.
=> issue: 3249310 Support only systemctl for vma service setup/removal

.ci/matrix_job.yaml
Added build in Fedora 36 and RHEL 8.6 x86_64 containers, ubuntu20.04-inbox-aarch64 removed.
=> issue: 3325307 Fedora 36 added to CI OS list

src/vma/sock/sock-redirect.cpp
In reclaim buffer api - vma_socketxtreme_free_vma_packets we use reclaim_recv_buffers method which uses try_lock on the ring, but in case the lock has failed - buffers will not be returned.
The fix - in case the ring is locked - reclaim buffers to the global pool.
=> issue: 3525812 Fix buffer leak socketextreme

src/vma/lwip/tcp_in.c
TCP stream corruption
Equality checks in lwip on seqno related parameters must be done using special macros to a handle situations when seqno wraps around.
TCP stream corruption in case of OOO packets
=> issue: 3591039 Fixing lwip seqno wrap around condition

src/vma/lwip/pbuf.c, src/vma/lwip/pbuf.h, src/vma/lwip/tcp_in.c
With LRO/GRO, TCP segments can be large and 16bit type is not enough to fit possible offsets/lengths. This can lead to a type overflow and broken pbuf chains as result. Further, a broken chain breaks accounting of received data what leads to a warning or even a segfault.
Increase type length for pbuf_header() and the trimming code. This fixes pbuf chain. Also increase type length for pbuf_realloc() to avoid similar issues in the future.
Fix type overflow.
Bugfix.
=> issue: 3202977 Fix type overflow during trimming TCP seg

src/vma/dev/rfs_uc_tcp_gro.cpp, src/vma/dev/rfs_uc_tcp_gro.h, src/vma/lwip/tcp_out.c, src/vma/proto/mem_buf_desc.h, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_tcp.h
Chain of pbufs can contain some pbufs with ref count >=1 like in ooo or flow tag flows. While processing Rx packets we may split buffer chains and we increment ref count for the new head of the chain after the split.
It will cause a wrong ref count, and the buffer won't be reclaimed. Therefore we reset ref count 0 for chained mem_buf_desc in m_rx_pkt_ready_list except for the head. Related to issue 3231710.
=> issue: 3591039 Fix ref count for mem_buf chains

src/vma/dev/qp_mgr.cpp, src/vma/dev/qp_mgr.h, src/vma/dev/qp_mgr_eth_mlx5.h
VMA hangs infinitely in ring destruction
If the RQ is empty, ring destruction will loop inifintely.
See more details in commit message
Fixing infinitely hanging VMA
Try to fetch last posted wqe only if the RQ is not empty.
=> issue: 3604175 Fixing stuck empty rx ring cleanup

src/vma/sock/sockinfo.cpp
For rx flow create key basing on allocation logic during ring creation and store it in sockinfo object.
Use actual key (w/o or w/ migration sceanrio) from sockinfo object.
RM#3604029 
Bug fix.
=> issue: 3604029 Fix releasing ring flow

README.txt, src/vma/main.cpp, src/vma/sock/sock-redirect.cpp, src/vma/sock/sock-redirect.h, src/vma/sock/socket_fd_api.cpp, src/vma/sock/sockinfo_tcp.cpp, src/vma/sock/sockinfo_tcp.h, src/vma/util/sys_vars.cpp, src/vma/util/sys_vars.h
1. Stop processing TCP timers in the main thread.
2. Add a locking mechanism for incoming TCP connections that haven't been accepted yet by the application.
=> Issue: 3697720 Fixes for segmentation faults

src/vma/lwip/tcp.c, src/vma/sock/sockinfo_tcp.cpp
XLIO return 0 and errno 0 in case of Keep Alive timeout.
Kernel returns -1 and errno ETIMEOUT.
XLIO ignores lwip TIMEOUT error in sockinfo_tcp.
LWIP uses wrong err in case of keep-alive timeout (EABRT).
API correctness
=> issue: 3655436 Return ETIMEDOUT err for timed out socket

src/vma/proto/route_table_mgr.cpp, src/vma/proto/route_table_mgr.h, src/vma/proto/rule_table_mgr.cpp, src/vma/proto/rule_table_mgr.h
This fixes a few places that weren't updated from `unsigned char` to `uint32_t` when support for extended route and rule tables was done for issue 1214066 (a90d08dd5140e0cbc6b6a45ddf71ebda69bb4141)
Changes type for `table_id` from `unsigned char` -> `uint32_t` in more places.
Extended routing table IDs overflow when used in these functions since unsigned char can only contain values up to 255 (8 bits) but extended table IDs can be 32 bits.
=> issue: 1214066 Update some unsigned char -> uint32_t for table_id

src/vma/util/sysctl_reader.h
1. Probe and interval values may be negative in:
- /proc/sys/net/ipv4/tcp_keepalive_intvl
- /proc/sys/net/ipv4/tcp_keepalive_probe
2. Internally the values will be set to 0 if negative.
=> issue 3749337 Handle negative Keapalive params

.ci/matrix_job.yaml, .ci/proj_jjb.yaml
Changes related to migration of CI to Blossom Jenkins
Change proj_jjb.yaml and job_matrix.yaml to fit the new nbu jenkins master, to allow it to run on the new jenkins instance Remove tap archives from job matrix, as it is not in use by anyone and the plugin is not installed on the new Blossom master
Issue: HPCINFRA-2277
=> [CI] Migrate pipeline to Blossom

.ci/Jenkinsfile, .ci/matrix_job.yaml
BlackDuck scan fails due to ngci connecting to the old gerrit url, fix is made to both this repo and the ci-demo repo (Changes made in this PR: https://github.com/Mellanox/ci-demo/pull/90)
Add credentialsId to login into the new gerrit url
skipDockerDaemonCheck configuration provided by the gerrit team.
Issue: HPCINFRA-2289
=> issue: 3977246 ngci connecting to the wrong url

src/vma/util/vma_list.h
C++20 has changed the syntax for nested template constructors:
```
In file included from ../../src/vma/proto/mem_buf_desc.h:39,
from ../../src/vma/util/utils.h:47,
from vlogger.cpp:46:
../../src/vma/util/vma_list.h:210:31: error: template-id not allowed for constructor in C++20 [-Werror=template-id-cdtor]
210 |         vma_list_t<T, offset> (const vma_list_t<T, offset>& other) {
|                               ^
../../src/vma/util/vma_list.h:210:31: note: remove the '< >'
```
Fixes compilation with GCC 14 and C++20.
GCC 14 is the default compiler for RHEL 10 and Fedora 40, and newer.
=> Fix compilation with GCC 14

.ci/Jenkinsfile, .ci/do_release.sh, .ci/dockerfiles/Dockerfile.rhel8.6.release, .ci/pipeline/release_jjb.yaml, .ci/pipeline/release_matrix_job.yaml
Unti now, release process is done manually by the dev team. This process involves creating a tag on a commit that needs to be released, building that tag and copying the files to NFS location
The idea is to create a jenkins pipeline that will do the entire process with given inputs, This commit will commence phase 1 - doing the build and copying of packages created to NFS.
THE CREATION OF A RELEASE TAG ON A COMMIT IS NOT PART OF THIS PR
[HPCINFRA-1889](https://jirasw.nvidia.com/browse/HPCINFRA-1889)
Add release_jjb and the corosponding matrix file for a new pipeline definition, the release is run on rhel8.6
Add do_release.sh script to run the build and NFS copy to release the package
Add Dockerfile for release container with all dependencies installed
What kind of change does this PR …
=> issue: 4007026 - [CI] Release pipeline

.ci/do_release.sh, .ci/proj_jjb.yaml
The new release pipeline links the latest release to a file called latest release, the dev team requested this feature to be removed
Remove ln line from do_release script
Requested by the dev team
=> [CI] issue: 4007026 Remove latest file link from release script

.ci/matrix_job.yaml, .ci/pipeline/release_jjb.yaml, .ci/pipeline/release_matrix_job.yaml, .ci/pipeline/release_matrix_job_dr.yaml, .ci/proj_jjb.yaml, .ci/redmine_jjb.yaml
Secrets Scanner - rename Jenkins secrets IDs to human-readable format
Update Jenkins's secrets reference in CI
UUID format in secrets references confuses Secrets Scanner, which takes these data for passwords and fail.
=> issue: 4072930 Secrets Scanner - rename Jenkins secrets IDs 

.ci/matrix_job.yaml, .ci/redmine_matrix_job.yaml
issue: HPCINFRA-2469
Remove support for old OS images
- removed ubuntu20.x
- removed branches running on r-aa-fatty22-005 and r-aa-fatty22-005 (rhel7,5 and ubuntu16.04 accordingly)
Old OS versions are not supported by DOCA which we're going to switch to
Update job_matrix config
=> issue HPCINFRA-2469: [CI] remove support for old OS images

.ci/pipeline/dr_weekly_jjb.yaml, .ci/pipeline/dr_weekly_matrix.yaml
This change implements weekly builds on the DR site
weekly_laucher Job that stays unchanged and triggers the release job on the DR site
We need to do periodic checks of DR Jenkins instance and Infra entities by running CI workloads
Issue: HPCINFRA-2975
weekly_laucher scheduled job
=> issue: 4208807 Implement weekly builds on DR site

src/vma/proto/netlink_socket_mgr.h, src/vma/proto/route_table_mgr.cpp, src/vma/proto/route_table_mgr.h, src/vma/proto/rule_table_mgr.cpp, src/vma/proto/rule_table_mgr.h, src/vma/proto/rule_val.cpp, src/vma/proto/rule_val.h
Kernel 6.10 netlink has breaked VMA functionality. 
Transitioned to libnl - an abstraction that wraps netlink.
This both solves the issue and makes us more robust.
Build routing and rules table using libnl instead of netlink.
removed protocol field in rule_val as:
1. it wasn't in use.
2. the api to populate it in libnl - `rtnl_rule_get_protocol` isn't available in sles on the CI.
solves https://redmine.mellanox.com/issues/4223310
Tested on kernel 5.21 and kernel 6.10.
=> issue: 4223310 VMA support for kernel 6.10

.ci/matrix_job.yaml
We want to move all build steps and test CI steps to the Blossom K8s cluster.
Switch to the Blossom K8s cluster.
Blossom cluster is more stable, visibly managed and has 24/7 SRE/NOC support.
=> [CI] issue: 4283986 Move build steps to Blossom K8s

contrib/jenkins_tests/gtest.sh, src/vma/dev/allocator.cpp, src/vma/dev/allocator.h, src/vma/dev/buffer_pool.cpp, src/vma/dev/buffer_pool.h, src/vma/libvma.c, src/vma/main.cpp, src/vma/sock/sock-redirect.cpp, src/vma/util/sys_vars.cpp, src/vma/util/sys_vars.h, src/vma/vma_extra.h, tests/gtest/Makefile.am, tests/gtest/common/def.h, tests/gtest/vma/vma_ioctl.cc, tests/gtest/vma/vma_poll.cc
This function allows to communicate with library using extendable protocol
based on struct cmshdr.
Ancillary data is a sequence of cmsghdr structures with appended data.
The sequence of cmsghdr structures should never be accessed directly.
Instead, use only the following macros: CMSG_ALIGN, CMSG_SPACE, CMSG_DATA,
CMSG_LEN.
Added ioctl command message as CMSG_VMA_IOCTL_USER_ALLOC with format
1. uint8_t - control flags
2. uintptr_t - pointer to memory allocation function
3. uintptr_t - pointer to memory free function
control flags manage usage of memory functions for global rx, tx  memory pools.
It allows an user to get full control on requested memory.
**Important note:**
- User should deallocate memory after unloading library.
- CMSG_VMA_IOCTL_USER_ALLOC must be called before the library …
=> issue: 4251780 Add ioctl() extra api

.ci/do_release.sh
The name of the folder created for the package in the release process is wrong, and there is no link created to the package under source_rpms
Change release folder name from libvma_v_<version> to vma_v_<version> 
Create semilink from package release folder to source_rpms folder.
Issue: HPCINFRA-3267
=> Issue: 4332286 Release path change and source_rpms semilink

.ci/dockerfiles/Dockerfile.rhel9.4, .ci/matrix_job.yaml
Verify VMA on Grace Hopper with RH9.4
Add new rhel9.4 Dockerfile - supports both x86_64 and aarch64 
Add definition for rhel9.4 aarch64 under matrix job
[HPCINFRA-3259](https://jirasw.nvidia.com/browse/HPCINFRA-3259)
https://redmine.mellanox.com/issues/4322501#change-35520800
=> [CI] issue: 4322501 Add rhel9.4 aarch64 as build container

.ci/pipeline/release_matrix_job.yaml
DRP daily release test is failing due to a missing source_rpms folder under /tmp
Add empty volume under /tmp/source_rpms required by the soft link created at the end of the process
Bugfix for DR specifically after the softlink changes added in https://github.com/Mellanox/libvma/pull/1112
=> Issue: 4332286 Bugfix - DR release pipeline fails on /tmp test

src/vma/sock/sock-redirect.cpp
vma_get_api()->thread_offload() can be called before the 1st socket() syscall. In this case VMA is in uninitialized state and the thread_offload() call fails with -1.
Call DO_GLOBAL_CTORS() in the vma_thread_offload() to guarantee the initialized state in all scenarios.
Until VMA 9.8.70, the initialization was done in the vma_get_api() call, however, it was removed due to external allocator support which requires uninitialized state to guarantee buffers allocation with the configured allocator.
Fix vma_thread_offload() failure is called before the 1st socket() syscall. 
Bugfix
=> issue: 4337575 Init VMA in vma_thread_offload()

.ci/blackduck_source.sh, .ci/dockerfiles/Dockerfile.rhel8.6, .ci/matrix_job.yaml
Replaced NGCI-based BlackDuck source scan with manual BlackDuck script execution
This change removes the NGCI module previously used for running BlackDuck source scans
NGCI relied on a Gerrit user token for cloning BlackDuck, which was subject to frequent rotation and caused recurring CI failures.
We move to manual scan execution via custom script using a service account with stable ssh-based authentaction.
=> [CI] issue: 4411941 BlackDuck scan startup fix

.ci/matrix_job.yaml
Replaced NGCI-based BlackDuck source scan with manual BlackDuck script execution
This change removes the NGCI module previously used for running BlackDuck source scans
NGCI relied on a Gerrit user token for cloning BlackDuck, which was subject to frequent rotation and caused recurring CI failures.
We move to manual scan execution via custom script using a service account with stable SSH-based authentication.
=> [CI] issue: 4416570 Move hardcoded BD token to Jenkins Credentials

.ci/do_release.sh, contrib/build_pkg.sh
Released packed should be tar.gz instead of src.rpm, with a small change to the dir stucture
For now we will create both the src.rpm and the tar.gz created in the build_pkg.sh , and moves it to the release folder.
Pointers to the new tar.gz file are not being created by the script
Move libvma.spec to the root of the directory being compressed. 
Remove libvma.spec from contrib/scripts/libvma.spec
Issue #4377705
=> [CI] issue #4377705: Create tar.gz from src.rpm
